---
title: The [A-Z] of contacting professors for graduate admissions
description: from [Reddit](https://www.reddit.com/r/gradadmissions/comments/oeabbf/the_az_of_contacting_professors_for_graduate/)
format:
  html: 
    grid:
      body-width: 600px
---
# Why email ?
Contacting professors before/ during the admissions cycle is no longer a "hack" but more of a necessity. The competition to secure seats in different programs all over the world is increasing every year which makes this so important. I will be covering a few points one needs to take care of while sending out emails. I have hugely improved my own emails over the past 2 years. This year, I will be starting a fully-funded MSc+PhD at the University of Edinburgh.

First of all, let's briefly talk about the benefits of contacting professors 

- It makes them aware of you and about the fact that you are applying in this admissions cycle.

- It gives your profile a chance to stand out amongst the heap of applications.

- It gives you an idea if the professor is looking for new graduate students (MS/ PhD) or if applying to them would be worthwhile 

- It is possible that the professor loved your profile but simply doesn't have the funding or space in their group.

There are a few main ideas that one needs to keep in mind while sending out emails 

- Professors are extremely busy and their inboxes are flooded with requests. Hence, you need to be brief and clear with your request/ questions.

Check this [tweet](https://twitter.com/thegautamkamath/status/1411030701307277315) by Prof. Gautam Kamath at Waterloo to get an idea about how many emails professors get in a day 


Professors CANNOT admit your application for a program. This decision is made by the admissions committee. The professors can merely forward your application with interest to them which increases your chances.

# Email template and sample

In order to write an effective email that catches attention while accommodating the above points, I like to follow a simple template where I ask indirect questions that gives me an idea about the answers I am looking for. The template is as follows

---

Dear Professor XXXX

[Your Introduction]

[Your current position and 1-2 Lines mentioning your prior work that aligns with the professor's research] - This allows your profile to stand out and gives it a chance to be remembered.

[What led you to the professor, his research and his group] - This shows you have done your due research and are not sending blind, cold emails. Also, augments their interest in your profile.

[2-3 Questions in bullet points that answer your real questions indirectly]

[Your resume/ CV at the end to give a detailed background about your work] - The professor reaches this part only if they found the previous points genuine and interesting.

Warm Regards,

Your Name
---


Here is an actual email that I have sent multiple times:

---
Dear Professor XXXX

My name is Raman Dutt, a graduate of XXXX University <insert URL>. I am currently working as a research associate at HITI Lab <insert URL> at Emory University with Professor A <insert URL> and Professor B <insert URL>. My research includes applications of deep learning for medical image analysis, with a special focus on domain adaptation and transfer learning. I have read your intriguing work on medical image analysis (such as <URL> and <URL>) and I am highly motivated to pursue an MS/ PhD in Artificial Intelligence. Here are a few questions 

- Are you looking for new graduate students for Fall'21?

- Which department should I apply to be able to best work in your lab?

- What qualities/ skills do you prefer in a student?

I've attached my resume to give you more information about my background. 
Thank you for your consideration!
Sincerely,
Raman Dutt <URL to personal website/ Google scholar/ Github/ etc>
---

Including links makes your email crisp and enriched with information.

**Tailoring the email by including links to the professor's previous or recent papers makes it 10 times more impactful.**
You have gotten an idea if the professor is looking for new students. If yes, mention his name in the SoP. If no, find more people with similar interests.
The professor might know your current mentors and that will make your application more interesting.
Remember to be genuine. If you randomly select any of their papers that don't have any correlation with your work, you will simply sound desperate.
ALWAYS, remember to schedule your email according to the time zone of the professor. I did the same with every email of mine so that it landed at the top of their inbox the next morning. **The best time to contact would be 8-8:30 am in the morning on weekdays (Monday - Friday)**.

Here is a [link](https://www.reddit.com/r/gradadmissions/comments/oc9gt7/advice_from_someone_who_got_rejected_from_all/) to another post which talks about best practices for a successful graduate application: 

For any questions, you can contact me on Twitter.

All the very best everyone!

# Addendum

## 1

u/ConfusedCuddlefish had some great points to add

For some programs, it is required that a professor vouch and agree to work with a student for them to be admitted, so professors can have their own mini-application process to screen out their list of candidates before your application is even sent to the department for the regular admissions screening. A piece of advice for prospective students is as soon while you're looking for programs to apply to, pay close attention to their requirements and if you need faculty approval for admission.

Also, as for following up on emails, I've found that waiting two weeks is a good standard metric, and you can just reply to your original email to keep the same email thread and do:

"Hello Dr. X, I am greatly interested in your work and would love to talk with you to discuss your research and whether or not you are seeking new graduate students for the <Term> semester."

If you're emailing during a known exam season, I also found that if I asked if there was a better time to contact them, I seemed to have more responses (anecdotally).

If you have a Gmail account, there is a schedule send function that I found immensely helpful to be able to write emails at any time and send them precisely when I wanted to. Again anecdotal but I had a lot more success getting replies and quick replies when I scheduled emails to be sent **either late Monday morning or Tuesday morning**.

## 2


A few thoughts, not necessarily in order of the OP:

-- I wonder if some of this is cultural? The following critiques apply to the U.S.

-- This might be U.S.-centric, but "highly motivated" impresses roughly zero people. It is also redundant. You are demonstrating your motivation by reaching out to the professor.

-- Including links in the initial email might trip spam detection, sending your email to the trash folder. I also seriously doubt a professor is going to bother to look, given how busy they are. If they are curious enough, they will ask. Otherwise, they will just take your word for it.

-- Asking a professor if they will be taking on student[s] is a good idea, but asking if they know which Department you should apply to in the initial inquiry is fishing. If they bother to respond, they will either tell you out-right where you might be a better fit, or, you can pop this question in a later email once rapport has been established. As for asking about the qualities and skills they are looking for, once again this can come up in further correspondence, but is a bit much for the initial email. At least in the U.S., anyways. If you are an international applicant, it might be okay.

-- Including links to the professor's own works is.... why? They know what they wrote, and when. In the U.S., they will likely have a [short] list of published works on their websites or lab pages. It is also in their CVs, which are also posted on university websites.

-- Pick one: either you are motivated to pursue the MS or the Ph.D. Saying you are 'highly motivated to pursue an MS/Ph.D.' sounds like you are not sure which, or that you are desperate. In your case (the OPs), you applied to a combined MS/Ph.D. program, but this is the Internet, and Reddit: some will copy it verbatim (hopefully changing the name, of course). If you are unsure, just state that you are unsure and are considering the MS first. Some professors do not take on Master's students and some Ph.D. programs prefer to see an MS first.

-- "Cold" inquires are perfectly okay, especially if you mention you are doing so as a first step towards applying.

-- For many of the subfields within Biology, in particular Ecology (where it is mostly required) and for ecology-related fields (marine biology, biological oceanography, animal behavior, zoology, and so on), individual professors can and do admit students directly. In reality, you are being hired by the professor to work in their lab, for them.

-- Once again this might be specific to the U.S.: contacting professors in some fields is the norm (and may be required), while in others it is still unheard of. If you are interested in pursuing an advanced degree in STEM, go ahead and do it. If not looking at STEM, I would suggest contacting the program director or department chair and ask if it would be appropriate before sending off emails.

A caveat to this is that most professors seem to like talking about their associated programs. So, an initial inquiry into the program in general might be okay.

# Other Resources
- https://lucklab.ucdavis.edu/blog/2018/9/17/emailing-faculty
- 