---
title: How to prepare graduate school interview?
description: from Jin-Bin Huang
---

**Be prepared**

Some faculty may say "it's just chatting". THEY LIED! They will seriously evaluate the interaction with you during the call and form their opinions. Prepare slides summarizing your work and practice commonly asked questions (e.g., research, goals, why here).

**Express interest**

Dept. often can only admit a limited number of applicants. So they have to strategize who to give out the offers. The level of interests you express plays an important role. You won't get an offer if the dept. feels that the chance of recruiting you is low.

**Be organized**

The email correspondences with the faculty send out signals of how organized you are. Send concise, clear, well-formatted emails. Share your availability with specific time slots (converted to their timezone). Help them better manage their time.

**Ask questions**

The interview is bi-directional. You are also interviewing with the faculty/university. Do your homework. Ask specific questions that matter most to you (see also [list of potential questions](https://drive.google.com/file/d/1o2ZTrUQYDXKbMlcmSH8lE-MW5vOX77PR/view)).

**Be yourself**

Don't need to freak out. You don't need to change anything or wear formal suit for these interviews. The potential advisor is interested in knowing about you and your research. Show your true color.