---
title: Module 9 - Generative Models
tbl-colwidths: [35,120,30,50,70]
title-block-banner: true
---

# Course Schedule and Resources

## Main lessons

| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| <span class="badge rounded-pill bg-success">Assignment</span>    | [Style Transfer Exercise](https://drive.google.com/file/d/1QPK7vA82XTC3tUaNfPAiFeD8VFZDAu7s/view?usp=drive_link)     | TA Khoa          |Due: 17 March, 2024 <br/> [[solution](https://drive.google.com/file/d/1X5THF7DzEwyabheAi56cFn4bjFp2iOs2/view?usp=drive_link)]     |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Basic Style Transfer](https://www.google.com/url?q=https://youtu.be/YktF-L5Y4eE&sa=D&source=editors&ust=1724832556756434&usg=AOvVaw0PO2w8W5IMVUiqK719sVNa)       | Dr. Vinh         | [240306-23M09-MC](https://drive.google.com/drive/folders/1JVrMc3X0O1o6RAq0iqSPd_lKfHMsIzxm?usp=drive_link)|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Multimodal Style Transfer](https://www.google.com/url?q=https://youtu.be/NYYZi3y_GcU&sa=D&source=editors&ust=1724832556756743&usg=AOvVaw1o0959BFb5Of-7TFiY650x)   | Dr. Vinh         | [240308-23M09-MC](https://drive.google.com/drive/folders/1muadwqQQ2w1_6v9suVfNHD5A7VxlLg12?usp=drive_link)|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [TA Exercise](https://www.google.com/url?q=https://youtu.be/fmWOQo_ru2c&sa=D&source=editors&ust=1724832556757041&usg=AOvVaw1URvhQeOMpbB9MxvRDalxd)  | TA Khoa          | 240310-23M09-MC|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [TA Exercise](https://www.google.com/url?q=https://youtu.be/TNDtPtHz7Wo&sa=D&source=editors&ust=1724832556757323&usg=AOvVaw1ogn1fod5EboUIyGGWrwYl)  | TA Thái          | [240317-23M09-MC](https://drive.google.com/drive/folders/1GtIy16him1HvNEgasqHY3YwFLp4G-zY9?usp=drive_link)|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [GAN and DCGAN](https://www.google.com/url?q=https://youtu.be/Lpj4j8Vw_H8&sa=D&source=editors&ust=1724832556757650&usg=AOvVaw24V7DSybYICOi_4vFFu6mE)    | Dr. Vinh         | [240320-23M09-MC](https://drive.google.com/drive/folders/1Bc_1dzxUJ8_DvUv58ocuTNkUMeu02aIZ?usp=drive_link)|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Pix2Pix and CycleGAN](https://www.google.com/url?q=https://youtu.be/eEMzZKA8suw&sa=D&source=editors&ust=1724832556757958&usg=AOvVaw23eULYRNbrwPASwIj9kwlT)        | Dr. Vinh         | [240322-23M09-MC](https://drive.google.com/drive/folders/1pbTCg1Fvga4EGGhI-t0KVs3bYSio-CE6?usp=drive_link)|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [Text to Image Synthesis with DCGAN](https://www.google.com/url?q=https://youtu.be/rAsKchlROVY&sa=D&source=editors&ust=1724832556758245&usg=AOvVaw2aActh47cOnEGU5sGpQKjn) | TA Thái          | [240324-23M09-MC](https://drive.google.com/drive/folders/1SI_rxQ7yDB976ZAVXnpKHY6p1s6nsmNZ?usp=drive_link)| [[handout](https://drive.google.com/file/d/1aF96yqaWLzDwQwEf1jLUQmJ4j9_c45Y1/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1dtDpfWb1XypRUYOIA4MavXsMkVr-A1ZM/view?usp=drive_link)]      |
| <span class="badge rounded-pill bg-success">Assignment</span>    | [Image Inpainting with DDPMs](https://www.google.com/url?q=https://drive.google.com/file/d/137VozceS2H8V2tR1QOJDaTJ0b8SrXsxN/view?usp%3Ddrivesdk&sa=D&source=editors&ust=1724832556758541&usg=AOvVaw2EZUSnpWAYCeDtGC-ZY4-J)  | TA Thái          | [[handout](https://drive.google.com/file/d/1EApa6e51uBDoSlN8oQAFTvIGEv7vaikv/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1KISqbu-2Dn6uGHPGgLM3JPrOL-wmGLvG/view?usp=drive_link)]     |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Diffusion Models (1)](https://www.google.com/url?q=https://youtu.be/e_TYyoBkHus&sa=D&source=editors&ust=1724832556758835&usg=AOvVaw3nEMxpJNeaIcuPd3g0bklT)         | Dr. Đình Vinh    | [240327-23M09-MC](https://drive.google.com/drive/folders/1EaLZOeNHN6RH4N_IrPRtSjA0hIElX3_K?usp=drive_link)| Tutorial on Diffusion Models for Imaging and Vision |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Diffusion Models (2)](https://www.google.com/url?q=https://youtu.be/3ucd3fsVaIk&sa=D&source=editors&ust=1724832556759188&usg=AOvVaw3p0D2QLqOy6VYhSDryy79Q)         | Dr. Đình Vinh    | [240329-23M09-MC](https://drive.google.com/drive/folders/1QWKTj7IxxTbTAkjf40FE09M0scOSwqMR?usp=drive_link)|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [Diffusion-based Image Inpainting](https://www.google.com/url?q=https://youtu.be/9Y_sRfsEKdI&sa=D&source=editors&ust=1724832556759475&usg=AOvVaw0rtuVfY3ZpOAHoNi3ryDl2)   | TA Thái          | [240331-23M09-MC](https://drive.google.com/drive/folders/1pZDxNjzfJ4qnCHKfB1Cb_IaYIxZEpIPp?usp=drive_link)|[[handout](https://drive.google.com/file/d/1MQQcXm-N0X1Ja3ezPDZLshB4JF0MBAFY/view?usp=drive_link)]-[[solution](https://drive.google.com/file/d/11Q0SGDngxbD0yXAYTFr0I5toKS0PAjON/view?usp=drive_link)]     |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Project: VAE-based Image Colorization](https://www.google.com/url?q=https://youtu.be/aZVRG_ybkr0&sa=D&source=editors&ust=1724832556759762&usg=AOvVaw0IWhKLQO5Uc6qvg8ooyinJ)  | Dr. Tài          | [240403-23M09-MC](https://drive.google.com/drive/folders/18nd8N3fENCYCcFdYPiq5mfuOAERfErKM?usp=drive_link)|      |
| <span class="badge rounded-pill bg-warning">Project Tutorial</span> | [Project: Diffusion-based Image Colorization](https://www.google.com/url?q=https://youtu.be/EniYKDr10mg&sa=D&source=editors&ust=1724832556760062&usg=AOvVaw0LazRuYOc7sIcWwT5Sh_TX)    | Dr. Tài          |[240407-23M09-MC](https://drive.google.com/drive/folders/185nRgQAl79oDkTeYM1fTxehe43fXBIaz?usp=drive_link)|[[handout](https://drive.google.com/file/d/1jTYIKAK3HeUJEGaEt5MDLZ9uSl4wde-9/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/15kauLW5LHcj0H099CJiFJPn6eOu26Vm2/view?usp=drive_link)]      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Stable Diffusion](https://www.google.com/url?q=https://youtu.be/y4P7JDgKCvU&sa=D&source=editors&ust=1724832556760562&usg=AOvVaw37RV_Bp8RVueNm7TrTZDvZ)  | Dr. Đình Vinh    | [240410-23M09-MC](https://drive.google.com/drive/folders/17WIzMu57Ilqf4n9iUSv4F4isCGQ22Eus?usp=drive_link)|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Introduction to OpenAI's Sora](https://www.google.com/url?q=https://youtu.be/4aDFyY8dAkI&sa=D&source=editors&ust=1724832556760868&usg=AOvVaw2jmMs7nqKsxzTz8HfjNhYT)          | Dr. Đình Vinh    | [240412-23M09-MC](https://drive.google.com/drive/folders/17W4NtSvVuArPxGVcPbZPrO_FUdIOVqyw?usp=drive_link)|      |
| <span class="badge rounded-pill bg-warning">Project Tutorial</span> | [Text to Image Synthesis with Stable Diffusion (and CLIP)](https://www.google.com/url?q=https://youtu.be/5JPrVLhkQjo&sa=D&source=editors&ust=1724832556761158&usg=AOvVaw0KHPXkgADVKvAnDVDkuNwb) | TA Thái  | [240414-23M09-MC](https://drive.google.com/drive/folders/12l5fe9R08z7qW-tgHBZ3XSoK4dUDQGll?usp=drive_link)|[[handout](https://drive.google.com/file/d/1pZTyPXpMzBHGlwcdLbdlS6P0HVGyh9cJ/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/16SVm1Hti-tgnaM2sLXu6RlcZwsJn9iz7/view?usp=drive_link)]      |


##  Extra class: Introduction to Large Language Models (LLMs)
| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| LLMs          | [Training a minChatGPT](https://www.google.com/url?q=https://youtu.be/kEzLMnpw5zE&sa=D&source=editors&ust=1724832556761518&usg=AOvVaw0xX0tfQ4TMfKqRPXPVSXk1)        | TA Thái          | [240406-23M10-EC1](https://drive.google.com/drive/folders/1bHEvixDSp_Ya-M1tzUUYwDGMR0i7IRpv?usp=drive_link)          |      |
| LLMs          | [LLM Finetuning for Math Solver](https://www.google.com/url?q=https://youtu.be/pB2gb7e_N18&sa=D&source=editors&ust=1724832556761827&usg=AOvVaw1kyLx6mvb9-nK__-Kwzu7h)          | TA Thắng         | [240413-23M10-EC1](https://drive.google.com/drive/folders/1RkdzGkCMmMGisZRJ11btzXGhjiu0nmyD?usp=drive_link)          |      |


## Extra class: MLOps
| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| <span class="badge rounded-pill bg-info">MLOps</span>  | [Model Pruning](https://www.google.com/url?q=https://youtu.be/dOgaMtt_fhM&sa=D&source=editors&ust=1724832556762176&usg=AOvVaw082dQxxMvW5E1ErDrW_CVH)                   | TA Bách          | [240309-23M09-EC1](https://drive.google.com/drive/folders/1EIEFV1dWoqZ10IzZn8H1a3mYwAdIBxFD?usp=drive_link)   |
| <span class="badge rounded-pill bg-info">MLOps</span>  | [Mobile Deployment](https://www.google.com/url?q=https://youtu.be/z5w0806ThLU&sa=D&source=editors&ust=1724832556762460&usg=AOvVaw2ve77WcUxRREQEchr1d1zx)               | Dr. Đình Vinh    | [240316-23M09-EC1](https://drive.google.com/drive/folders/17rUkFODK3HmdI_s7Scys0y1kqbKrmbmj?usp=drive_link)   |
| <span class="badge rounded-pill bg-info">MLOps</span>  | [Web Deployment](https://www.google.com/url?q=https://youtu.be/B55Jb7enrq8&sa=D&source=editors&ust=1724832556762742&usg=AOvVaw1aVpcvXHuHsI8toB8o4OHE)                  | Dr. Đình Vinh    | [240323-23M09-EC1](https://drive.google.com/drive/folders/1d6ChPC8Ri2l-O7YMEJ67SetHREqCdPLm?usp=drive_link)   |
| <span class="badge rounded-pill bg-info">MLOps</span>  | [Deployment as a Service (API)](https://www.google.com/url?q=https://youtu.be/o0FacL81Azo&sa=D&source=editors&ust=1724832556763026&usg=AOvVaw336AdobiV4bLKxLtSA3SJq)   | TA Thắng         | [240330-23M09-EC1](https://drive.google.com/drive/folders/1Suv0cTn4bEbfJ4rEcCiPwRW54IPRDslG?usp=drive_link)   |

## Seminar
| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| Seminar| [Seminar: XAI](https://www.google.com/url?q=https://youtu.be/RKcPFwzkkLs&sa=D&source=editors&ust=1724832556763354&usg=AOvVaw1KED7sW6alNyrjUl1QF8Gh)                    | Dr. Anh Nguyen   | [240405-23M09-MC](https://drive.google.com/drive/folders/1_KoRgGcEat4gt-wqA63rksHoFbFo_gpU?usp=drive_link)    |
