---
title: Module 6 - Introduction to Deep Learning
tbl-colwidths: [25,47,80,40,50,70]
title-block-banner: true
---

# Course schedule and Material

## Main lessons
| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|
| 06/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| [Convolutional Neural Network Exercise](https://drive.google.com/file/d/1YmC4RllUrfV8LWyHyEogMQg6NBIKhh24/view?usp=drive_link)  | TA Thái      | Due: 12 Nov, 2023 <br/> [[solution](https://drive.google.com/file/d/1N6nWE5n-slequYA0_SfNl9Ink5LjTMCh/view?usp=drive_link)] |       |
| 08/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic CNN (1)](https://www.youtube.com/watch?v=6pC_uYiwb1s)    | Dr. Vinh     | [231108](https://drive.google.com/drive/folders/18RDEw9VxQO97FHSHGkLokHSE2GsnXukm?usp=drive_link)   | [CS231N Note] [CNN Explainer]          |
| 10/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic CNN (2)](https://www.youtube.com/watch?v=K2h27Nd9cFc)    | Dr. Vinh     | [231110](https://drive.google.com/drive/folders/10UXl7r217T296hn60UMgrZR8Hgl-U6PH?usp=drive_link)   |       |
| 12/11/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.youtube.com/watch?v=FojbBIDACD8)      | TA Thắng     | [231112](https://drive.google.com/drive/folders/11-GChRVSStsuRWJSYrNjAcpzW7sLLmFz?usp=drive_link)   |       |
| 13/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| [Convolutional Neural Network Exercise](https://drive.google.com/file/d/1xYeWQ8iFWlzoHxS70TF5rmsWXktVrKUJ/view?usp=drive_link)  | TA Thắng     | Due: 19 Nov, 2023 <br/> [[solution](https://drive.google.com/file/d/1y28QsZqnTvrgazWCqb3zmZSfNw57UJ17/view?usp=drive_link)] |       |
| 15/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [CNN Training](https://www.youtube.com/watch?v=WScW5CWOagE)     | Dr. Vinh     | [231115](https://drive.google.com/drive/folders/16glvYyEv-Q3v6tkEKezrpIcrvAgVNYio?usp=drive_link)   | [VGG Paper]      |
| 17/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [CNN Generalization](https://www.youtube.com/watch?v=Tcdw6E8Q_as)          | Dr. Vinh     | [231117](https://drive.google.com/drive/folders/1ccxvcWjG71R5qq0a79BrbUnOOQchsIkP?usp=drive_link)   |       |
| 19/11/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://youtu.be/ZZ67uJBQKJI)      | TA Thắng     | [231119](https://drive.google.com/drive/folders/1c-arzuTYMR5gay2tGdHkiTqULSrt5joc?usp=drive_link)   |       |
| 20/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| [Pretrained Models for Image Exercise](https://drive.google.com/file/d/1GlX4ZZPoMfs29d1BlqXNh5oqnL7MZenP/view?usp=drive_link)   | TA Thắng     | Due: 26 Nov, 2023 <br/> [[solution](https://drive.google.com/file/d/1J-96S5yF2PNOTYhUmvvU15cPDiCR4FaE/view?usp=drive_link)] |       |
| 22/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Advanced CNN Architecture](https://www.youtube.com/watch?v=GFMbC1HdMsM)   | Dr. Vinh     | [231122](https://drive.google.com/drive/folders/1jCmr-C0SEe4pChdGkTEAj1MNkZVrxJK-?usp=drive_link)   |       |
| 24/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Transfer Learning for CNN](https://www.youtube.com/watch?v=xPdmbOfzqNA)   | Dr. Vinh     | [231124](https://drive.google.com/drive/folders/1ti302PbenG4eIUi27P2ZgceMgeVRw7nd?usp=drive_link)   |       |
| 26/11/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.youtube.com/watch?v=9naw1lJrKl4)      | TA Thái      | [231126](https://drive.google.com/drive/folders/1tP0LTbKv1e85c37Lt-vkhiAaTPxXvESz?usp=drive_link)   |       |
| 27/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| [Recurrent Neural Network Exercise](https://drive.google.com/file/d/1V4cZAt-SxdIKDpcJ2aQ-axQMWLTPTDDf/view?usp=drive_link)      | TA Thắng     | Due: 03 Dec, 2023 <br/> [[solution](https://drive.google.com/file/d/12Ce5LvmZ2qluuRXcevZ3DGGUY0XMgpHb/view?usp=drive_link)]          |       |
| 29/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic RNN/LSTM (Time series and Text)](https://www.youtube.com/watch?v=jH3h_FrncU8)  | Dr. Vinh     | [231129](https://drive.google.com/drive/folders/1z7Af-ge9yoZv1OKIHc7iJm1PvsQepl0E?usp=drive_link)   |       |
| 01/12/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic RNN/LSTM (Time series and Text)](https://www.youtube.com/watch?v=b3dVz7d7Qt0)  | Dr. Vinh     | [231201](https://drive.google.com/drive/folders/1OaE2PZQcA5I_tJYoKphbtw2B37bt_I8t?usp=drive_link)   |       |
| 03/12/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.youtube.com/watch?v=N05jwQLMdyc)      | TA Thắng     | [231203](https://drive.google.com/drive/folders/1cwHRPBo93i-TpWmbstFnYgwkIjkYajto?usp=drive_link)   |       |
| 04/12/23| <span class="badge rounded-pill bg-success">Assignment</span>| [Transformer Application Exercise](https://drive.google.com/file/d/1hfu0x762s8rUT8WvhGHreeJQ5ACdt1ib/view?usp=drive_link)       | TA Thái   | Due: 10 Dec, 2023 <br/> [[solution](https://drive.google.com/file/d/1ig_WMTcRWUl5MQjABd1zHwn6Xtapxixy/view?usp=drive_link)]         |       |
| 06/12/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Transformer (Encoder - Text Classification)](https://www.youtube.com/watch?v=V_WnoOvYxMQ)       | Dr. Vinh     | [231206](https://drive.google.com/drive/folders/1YrgeE3DmEHQAZ2Gr8Ap0nFs8ZB_II24_?usp=drive_link)   | BERT Readings    |
| 08/12/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Transformer for Image and Time series Data](https://www.youtube.com/watch?v=Sql8bAPGI_U)        | Dr. Vinh     | [231208](https://drive.google.com/drive/folders/1C8UQd8T6ISEjfFJomJICY7od8JEL1nnw?usp=drive_link)   |       |
| 13/12/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Image Project: OCR with YOLOv8 and CNN (Scene Text Recognition)](https://www.youtube.com/watch?v=SnYz7k5fRwM) | TA Thắng     | [231213](https://drive.google.com/drive/folders/19c0A5nIN62H2QOm1TB6F0hNIWRE7MXhe?usp=drive_link)   | [handout](https://drive.google.com/file/d/1gWovZUKSHli3KqInnIzqjZfxgX9Ebw5i/view?usp=drive_link) - [solution](https://drive.google.com/file/d/1c5Gh5hgu2zToQglJKthhEzp5lpW0ZTAu/view?usp=drive_link)      |
| 15/12/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Image-text Project: VQA](https://www.youtube.com/watch?v=FKCr83VpQ4w)     | TA Thắng     | [231215](https://drive.google.com/drive/folders/1YjunCkx7BsxMkAe6Ld_2h-nym-2t79II?usp=drive_link)   |[handout](https://drive.google.com/file/d/13CLe4ZGw7Ut5NHPONbx7LyPinsvdiX00/view?usp=drive_link) - [solution](https://drive.google.com/file/d/1GYnNTdTER9-b6UANDb-YcSLjLNEsWnmP/view?usp=drive_link)       |
| 17/12/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Time-series forecasting project](https://www.youtube.com/watch?v=3jxk1udOBik)        | Dr. Đình Vinh| [231217](https://drive.google.com/drive/folders/1FsOigyi37v95OVi9NRwktItKTRtxs5eT?usp=drive_link)   | [handout](https://drive.google.com/file/d/1wcpWm5URs80Y0KnQw3XW8CCyu7FJgseK/view?usp=drive_link) - [solution](https://drive.google.com/file/d/1NO7A4LX1CQ5TW4OfEnB-PHF6g-TRkI2i/view?usp=drive_link)      |

## Competition Training

| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|
| 09/11/23| <span class="badge rounded-pill bg-warning">Competition</span>| [Zalo AI](https://www.youtube.com/watch?v=sEbWP2JmUtM)          | TA Hùng      | [231109](https://drive.google.com/drive/folders/1CkGOlJTDjBZ132AvzNT8xD73iKR3TF4b?usp=drive_link)   |       |
| 16/11/23| <span class="badge rounded-pill bg-warning">Competition</span>| [Zalo AI](https://www.youtube.com/watch?v=VJpZBriXPog)          |   | [231116](https://drive.google.com/drive/folders/11LiFiYoGMlnQPzvvvDxFYdh9w3KSNTcT?usp=drive_link)   |       |

## Python Review
| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|       
| 07/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Introduction to CNN](https://www.youtube.com/watch?v=R2z38h40sGI)         | TA Thái      | [231107](https://drive.google.com/drive/folders/1Z61LQxSdLXEo3Pv_pr2mymjDIXaH9ccO?usp=drive_link)   |       |
| 14/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Advanced CNN](https://www.youtube.com/watch?v=hgDSSIT5xdo)     |TA Thái   | [231114](https://drive.google.com/drive/folders/1T-9LzUnAsvelq73GxnpOxmNtEDtyaGRs?usp=drive_link)   |       |
| 21/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [CNN and its variants](https://www.youtube.com/watch?v=iF0bjYTA20E)        |TA Thái   | [231121](https://drive.google.com/drive/folders/1LHbMsWZ8NoZYv5EJkwHdaSEYlnaYyYyt?usp=drive_link)   |       |
| 28/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Introduction to Transfer Learning](https://www.youtube.com/watch?v=WzbPAPAs1r4)      |TA Thái   | [231128](https://drive.google.com/drive/folders/18q8OFiLF87gj4bCIolRYLEFNX9oxGdI8?usp=drive_link)   |       |
| 05/12/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Introduction to Transformer](https://www.youtube.com/watch?v=m-nTyZ8AH1U) | TA Thái  | [231205](https://drive.google.com/drive/folders/1zyYeXRxVIOzJCFwa8U5SvxPNmJCUmLov?usp=drive_link)   | Generative AI exists because of the transformer |


## Extra class: Research & Paper Writing
| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|        
| 11/11/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [Research Idea - Brainstorming (1)](https://www.youtube.com/watch?v=txoSTaozyMM)      | Dr. Đình Vinh| [231111](https://drive.google.com/drive/folders/1GYTeCt5swU8X6H8UnVRBcmPTUe_g2-sm?usp=drive_link)   |       |
| 18/11/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [Research Idea - Brainstorming (2)](https://www.youtube.com/watch?v=wNcnxaTTckc)      |   | [231118](https://drive.google.com/drive/folders/13t1EwgbnqoeWtv5sVByVgdgPYUFwRwJg?usp=drive_link)   |       |
| 25/11/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to do Research (1)](https://www.youtube.com/watch?v=iDILV4nI3tM)      |   | [231125](https://drive.google.com/drive/folders/1cCP1orVZDUQR_Qcxf9BSMf--Letd1ALE?usp=drive_link)   |       |
| 02/12/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to do Research (2)](https://www.youtube.com/watch?v=f4J1pHjQNdU)      |   | [231202](https://drive.google.com/drive/folders/11zVxxS7FqwcR24KyFkzFBOVM1lbY5UO1?usp=drive_link)   |       |
| 09/12/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to do Research (3)](https://www.youtube.com/watch?v=zzOKcKvPx-0)      |   | [231209](https://drive.google.com/drive/folders/1g7XeWRMDKKKVS9eej30n95hEn1htfYtc?usp=drive_link)   |       |
|

## Seminar
| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|  
| 10/12/23| <span class="badge rounded-pill bg-info">Seminar</span> | [Transformers for Time series data](https://www.youtube.com/watch?v=Y-KDJZq1skI)      | Dr. Vinh     | [231210-1](https://drive.google.com/drive/folders/1SSE9fW8MAPARGy7Nl9gdp2nSpZ4QBNpK?usp=drive_link) |       |
| 17/12/23| <span class="badge rounded-pill bg-info">Seminar</span> | [Scholarship and Feature Extraction in Time Series Data](https://www.youtube.com/watch?v=SHIYAz0uLzw)       |   | [231217-1](https://drive.google.com/drive/folders/1gKRphEDWy0UTqHBGBM18f6ObOEAF7teD?usp=drive_link)         |       |
