---
title: Module 3 - Probability and Statistics for AI
tbl-colwidths: [25,47,80,40,50,70]
title-block-banner: true
---

# Course Schedule and Resources

## Main lesson


| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|------------------------------------------------------------------------|----------------|----------|-----------------|
| 18/07/23   | <span class="badge rounded-pill bg-success">Assignment</span> | [Probability Exercise](https://drive.google.com/file/d/1QWfngARqyx2b9a6A04HyhOKmsWmre7rG/view)| Dr. Đình Vinh  |  ||
| 19/07/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Basic Probability, Histogram and Image Enhancement](https://www.youtube.com/watch?v=_3Geo5GvqBk)    | Dr. Vinh | [230719](https://drive.google.com/drive/folders/11y0jzKVJvBzSIGSVxl1g1ljvYRcywfLf?usp=drive_link)   ||
| 21/07/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Naive Bayes Classifier](https://www.youtube.com/watch?v=6VLK-lCWLVQ)    | Dr. Vinh | [230721](https://drive.google.com/drive/folders/1XAIStROw6WxXP-M5NWntfx69B6lwhzxC?usp=drive_link)   ||
| 23/07/23   | <span class="badge rounded-pill bg-info">Exercise Session</span> | [TA-Exercise](https://www.youtube.com/watch?v=KwUBo4nKQpA) | Dr. Đình Vinh  | [230723](https://drive.google.com/drive/folders/1RJyEJM47lQXhiw4NVherABZP2rsPKBt_?usp=drive_link)   ||
| 31/07/23   | <span class="badge rounded-pill bg-success">Assignment</span> | [Statistic Exercise](https://drive.google.com/file/d/15yY-SPtzUwl_4jl3Bnfg6CtzCShlh0rp/view)  | Dr. Đình Vinh  | [Solution](https://drive.google.com/file/d/19jcxudMDeis2394OdHvup673KhdxZD8u/view?usp=drive_link) ||
| 26/07/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Basic Statistics and Correlation Coefficient (Basic Tracking)](https://www.youtube.com/watch?v=jJyKPBKCZQI)  | Dr. Vinh | [230726](https://drive.google.com/drive/folders/1EPHOyuwIuYlYBV993OBXkf8GipsG7UpU?usp=drive_link)   ||
| 28/07/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Template Matching (Cosine Similarity vs. Correlation Coefficient)](https://youtu.be/x5z0TNgjlLU)| Dr. Đình Vinh  | [230728](https://drive.google.com/drive/folders/1bgFYIVV-e4OBxwZDnycA0qXERnzSb6uI?usp=drive_link)   ||
| 30/07/23   | <span class="badge rounded-pill bg-info">Exercise Session</span> | [TA-Exercise](https://www.youtube.com/watch?v=SkeI4eFR6KQ) | Dr. Đình Vinh  | [230730](https://drive.google.com/drive/folders/1Ww5Fkak79eQTGewH3bEjTBMSBL4GIS_E?usp=drive_link)   ||
| 31/07/23   | <span class="badge rounded-pill bg-success">Assignment</span> | [Genetic Algorithms and its Applications Exercise](https://drive.google.com/file/d/1j6GrKkqXnXyvFScnTEc0nR8zf1h_Up27/view)| Dr. Đình Vinh  | Due: 06 Aug 2023 [[solution](https://drive.google.com/file/d/1Qfq4FOcv7q6Kef-BgxacM4aR3XdppFl5/view?usp=drive_link)]  ||
| 02/08/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Randomness and Genetic Algorithms](https://youtu.be/vkjCagePwkk)    | Dr. Vinh | [230802](https://drive.google.com/drive/folders/173kJmQgxrcaQq2qZPVmpbiwfFfz8KBRu?usp=drive_link)   ||
| 04/08/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Genetic Algorithms (Optimization and Linear Regression)](https://www.youtube.com/watch?v=ujlajSEnMOk&feature=youtu.be)     | Dr. Vinh | [230804](https://drive.google.com/drive/folders/1Hkh_GZkh7dW06W8riE24eHrKdL9DRHF8?usp=drive_link)   ||
| 06/08/23   | <span class="badge rounded-pill bg-info">Exercise Session</span> | [TA-Exercise](https://www.youtube.com/watch?v=lXlROjef-6s) | Dr. Đình Vinh  | [230806](https://drive.google.com/drive/folders/1cTasfdBRvLkkPgcNB4aOIzdeEdlI7LL3?usp=drive_link)   ||
| 07/08/23   | <span class="badge rounded-pill bg-success">Assignment</span> | [Genetic Algorithms and its Applications Exercise](https://drive.google.com/file/d/1j6GrKkqXnXyvFScnTEc0nR8zf1h_Up27/view)| Dr. Đình Vinh  |  ||
| 07/08/23   | <span class="badge rounded-pill bg-info">Exercise Session</span> | [Data Analysis Exercise](https://drive.google.com/file/d/1pW6pdMDjPFrf4X1OG676DaIncS3xYWBo/view)    | TA Thắng | Due: 13 Aug, 2023  [[solution](https://drive.google.com/file/d/1TwUFXa066pY_x3dLI_gVP8udeYXh0yKS/view?usp=drive_link)] ||
| 09/08/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Data visualization and Data Analysis (1)](https://www.youtube.com/watch?v=qylk5_xJJ3E)   | Dr. Vinh | [230809](https://drive.google.com/drive/folders/13GY7R85C86c0ZmPwxu7kGxWKGmy7jLkR?usp=drive_link)   | |
| 11/08/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Data visualization and Data Analysis (2)](https://www.youtube.com/watch?v=WO7tyfpt-Kc)   | Dr. Vinh | [230811](https://drive.google.com/drive/folders/1ciRVtn5aSWzeO18LmanzDXVXsVQGtEa9?usp=drive_link)   ||
| 13/08/23   | <span class="badge rounded-pill bg-info">Exercise Session</span> | [TA-Exercise (Polar)](https://youtu.be/VvBjgYkdN5w) | TA Thắng | [230813](https://drive.google.com/drive/folders/1-KJy92a5fEL1-V7H6k89j-z_cEQgRVeU?usp=drive_link)   | [[Polar doc](https://pola-rs.github.io/polars-book/getting-started/intro/)]     |
:   {.striped .hover}

## Project Tutorial


| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|------------------------------------------------------------------------|----------------|----------|-----------------|
| 17/08/23   | <span class="badge rounded-pill bg-success">Assignment</span> | [Big Data Frameworks (1)](https://drive.google.com/file/d/1MCqtplXmS95CvjaUh95GPlyMw-lilNe5/view?usp=drive_link) | Dr. Đình Vinh  | Due: 20 Aug, 2023 [[solution](https://drive.google.com/file/d/1HKCBDE7wRi9inZlRB7Iii7cbI6YuG6Go/view?usp=drive_link)]   |  |
| 17/08/23   | <span class="badge rounded-pill bg-success">Assignment</span> | Big Data Frameworks (1) | Dr. Đình Vinh  |    |  |
| 17/08/23   | <span class="badge rounded-pill bg-info">Project Tutorial</span>| [Big Data Frameworks (1)](https://www.youtube.com/watch?v=Bv-_9yoj2LY) | Dr. Đình Vinh  | [230818](https://drive.google.com/drive/folders/1F7Fq_KcN0dLMkh3S-iNp7b-49-30hJ_U?usp=drive_link)   | [[LSFS and MapReduce](http://infolab.stanford.edu/~ullman/mmds/ch2n.pdf)] |
| 20/08/23   | <span class="badge rounded-pill bg-info">Project Tutorial</span>  | [Big Data Frameworks (2)](https://www.youtube.com/watch?v=gV-KJNPBIsI) | Dr. Đình Vinh  | [230820](https://drive.google.com/drive/folders/19_SqIZKQPnGuJmHbhQ9qtQC5EX9nnxqU?usp=drive_link)   ||
| 22/08/23   | <span class="badge rounded-pill bg-info">Project Tutorial</span>  | [Image Data Project: Image Retrieval](https://drive.google.com/file/d/1KjZ6VHiehGOoB_ZlrOAUkBJzyTO0IooM/view?usp=drivesdk)  | TA Thắng |  ||
| 23/08/23   | <span class="badge rounded-pill bg-info">Project Tutorial</span>  | [Big Data Frameworks (3)](https://www.youtube.com/watch?v=wLdHXNNDeh0) | Dr. Đình Vinh  | [230823](https://drive.google.com/drive/folders/18vEiTBJ9Q2SOelrW30rD08JCMt0u5X3d?usp=drive_link)   | [[C9, Feng 2021](https://runawayhorse001.github.io/LearningApacheSpark/pyspark.pdf#page=125)] |
| 25/08/23   |<span class="badge rounded-pill bg-info">Project Tutorial</span>  | [Image Data Project: Image Retrieval](https://www.youtube.com/watch?v=kqy-HF5moQM)  | TA Thắng | [230825](https://drive.google.com/drive/folders/1lPx522ThpI_0997u1gTFpjdNJLmRhr4k?usp=drive_link)   | [[solution](https://drive.google.com/file/d/1n2umD5Vv-hEqW2dF58gtkmwsJRHlD1KP/view?usp=drive_link)] [[VIT paper (Dosovitskiy et al., 2021)](https://arxiv.org/abs/2010.11929)] |
:   {.striped .hover}

## Extra class: Introduction to NLP


| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|------------------------------------------------------------------------|----------------|----------|-----------------|
| 29/07/23   | <span class="badge rounded-pill bg-info">NLP Introduction</span> | [Introduction, Preprocessing](https://www.youtube.com/watch?v=Mhr0Bsj0gDo)  | TA Thái| 230729   ||
| 05/08/23   | <span class="badge rounded-pill bg-info">NLP Introduction</span> | [Preprocessing, Tokenization](https://www.youtube.com/watch?v=QEXrwFc7gzQ)  |TA Thái     | [230805](https://drive.google.com/drive/folders/1oy2P4-j8uLSZiYDMo0-7YDNtsyYXmQfq?usp=drive_link)   | [[note](https://vietqnguyen.notion.site/AIO2023-Introduction-to-NLP-Notes-f97570244fef4fea9f85520fbe864832)] [[C2, Jurafsky et al., 2023](https://web.stanford.edu/~jurafsky/slp3/2.pdf)] |
| 12/08/23   | <span class="badge rounded-pill bg-info">NLP Introduction</span> | [Statistical Language Model](https://www.youtube.com/watch?v=WxHTNG4EvRo)| TA Thái    | [230812](https://drive.google.com/drive/folders/1tx5dxWwG9ec-hc8PNOzRwMbxxr_uDS5m?usp=drive_link)   | [[C3, Jurafsky et al., 2023](https://web.stanford.edu/~jurafsky/slp3/3.pdf)] [[Andrej Karpathy's Lecture](https://www.youtube.com/watch?v=PaCmpygFfXo)]  |
| 18/08/23   | <span class="badge rounded-pill bg-info">NLP Introduction</span> | [Part-of-Speech Tagging](https://www.youtube.com/watch?v=t90KOh4gvg4)    |  TA Thái   | [230819](https://drive.google.com/drive/folders/1rtW1m4QuG-WNGz3dlq3wXjakAG-tgKQ-?usp=drive_link)   | [[CA Jurafsky et al., 2023](https://web.stanford.edu/~jurafsky/slp3/A.pdf)] |
| 26/08/23   | <span class="badge rounded-pill bg-info">NLP Introduction</span> | [Constituency Parsing](https://www.youtube.com/watch?v=bye0wJatGQA)|  TA Thái   | [230826](https://drive.google.com/drive/folders/1J_dpvmghOrRCHDChvSv2c_qP1X7xMg0H?usp=drive_link)   ||
:   {.striped .hover}

## Python Tutorial Session


| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|------------------------------------------------------------------------|----------------|----------|-----------------|
| 18/07/23   | <span class="badge rounded-pill bg-dark">Python Support</span>   | [Probability](https://www.youtube.com/watch?v=qE5GcysXX_0) | TA Tiềm| [230718](https://drive.google.com/drive/folders/1NMOFel0S2mTnRzwXDQlAkmUYJdAV7bZX?usp=drive_link)   ||
| 25/07/23   | <span class="badge rounded-pill bg-dark">Python Support</span> | [Statistics](https://www.youtube.com/watch?v=2_Ec_GkaQdQ)  | TA Bảo | [230725](https://drive.google.com/drive/folders/10X_-Nfojn9Vfsl0_Hf-C6aiNqRgY2k4a?usp=drive_link)   ||
| 01/08/23   | <span class="badge rounded-pill bg-dark">Python Support</span> | [Genetic Algorithms](https://www.youtube.com/watch?v=QKkgphZDLlI)  | TA Tiềm| [230801](https://drive.google.com/drive/folders/1GWuzCuvbfiHcHG9vkQe-thmsMvXR2pDi?usp=drive_link)   ||
| 08/08/23   | <span class="badge rounded-pill bg-dark">Python Support</span> | [Pandas (1)](https://www.youtube.com/watch?v=mNC8xgpqr6g)  | TA Bảo | [230808](https://drive.google.com/drive/folders/1D9Mazy9tfgtIDfEyihBQUpq9tHHCEAnS?usp=drive_link)   ||
| 14/08/23   | <span class="badge rounded-pill bg-dark">Python Support</span> | [Pandas (2)](https://www.youtube.com/watch?v=Fl6XWH7OP3Y)  | TA Bảo | [230814](https://drive.google.com/drive/folders/1oeWRYoHqfCl2wErQ0cHXpg9P2Wnzhwlj?usp=drive_link)   | [[C7, McKinney 2023](https://wesmckinney.com/book/data-cleaning)] |
:   {.striped .hover}

## Competition Training


| <i class="bi bi-calendar-check"></i> Date| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor     | <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|------------|-----------------------------|------------------------------------------------------------------------|----------------|----------|-----------------|
| 20/07/23   | <span class="badge rounded-pill bg-warning">Competition</span>| [Tricks to improve performance](https://www.youtube.com/watch?v=Qc-pbbcVZak)| TA Hùng| [230720](https://drive.google.com/drive/folders/1anvZ8Jz3eCO5CoQFRRAHdoECYfdMCneA?usp=drive_link)   ||
| 27/07/23   | <span class="badge rounded-pill bg-warning">Competition</span> | [HCM AI Challenge](https://www.youtube.com/watch?v=0y6PKxh9_K4)    | TA Hùng    | [230727](https://drive.google.com/drive/folders/19OvLRrdojvra6iat0x1oph2R5DZr1YA9?usp=drive_link)   ||
| 03/08/23   | <span class="badge rounded-pill bg-warning">Competition</span> | [Web API + Docker](https://www.youtube.com/watch?v=GmarNkuwMyI)    | TA Hùng     | [230803](https://drive.google.com/drive/folders/15ACtPJ7Jrz14u3citmA5SBVXZt7p7c2E?usp=drive_link)  ||
| 17/08/23   | <span class="badge rounded-pill bg-warning">Competition</span>  | [Onnx](https://www.youtube.com/watch?v=qAZImjn6omw)     | TA Hùng    | [230817](https://drive.google.com/drive/folders/1KdEQoDp00jAraMvLGrB4tmvA8xJfFULD?usp=drive_link)   ||
| 24/08/23   | <span class="badge rounded-pill bg-warning">Competition</span> | [Semi-supervised Learning](https://www.youtube.com/watch?v=XC4OKloWlD8)  | TA Hùng     | [230824](https://drive.google.com/drive/folders/1UO1nOMuSd6BNHNwiWvDtIHCrBA5mM6zA?usp=drive_link)   | [[Lil'Log](https://lilianweng.github.io/posts/2021-12-05-semi-supervised/)] [[GitHub repo](https://github.com/yassouali/awesome-semi-supervised-learning)] [[Laine et al., 2016](https://arxiv.org/abs/1610.02242)] [[Tarvainen et al., 2017](https://arxiv.org/abs/1703.01780)] |
:   {.striped .hover}