---
title: Module 7 - Advanced Model Architectures for Computer Vision
tbl-colwidths: [30,100,40,50,60]
title-block-banner: true
---

# Course Schedule and Material

## Main lessons

| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor| <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-success">Assignment</span>| [Domain Conversion Exercise](https://drive.google.com/file/d/1OO8ObobhfTkkb6EU3qeU6YVCH3hfHpNR/view?usp=drive_link)  | TA Khoa | Due: 24 Dec, 2023 <br/> [[solution](https://drive.google.com/file/d/1quIlAEQ82X6SAKujt__BmJTHfTVkXp0b/view?usp=drive_link)]   | |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Domain Conversion - Denoising and Segmentation](https://www.google.com/url?q=https://youtu.be/lMs32sF7Ayo&sa=D&source=editors&ust=1724832556752327&usg=AOvVaw2nPS3yrULkk3EoPzpkn_9D)| Dr. Vinh| [231220-23M07MC](https://drive.google.com/drive/folders/1AkjYbMboEnf4mLO7dNqpqaioPRDIRHjO?usp=drive_link)| |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Domain Conversion - Colorization and Super Resolution](https://www.google.com/url?q=https://youtu.be/HqrKcKr7BO0&sa=D&source=editors&ust=1724832556752684&usg=AOvVaw25WYU9ymXVUyjBW4HTr5__)  | Dr. Vinh| [231222-23M07MC](https://drive.google.com/drive/folders/1KfKrrjalVzD2RXo9HpHCVjXJabLok2lT?usp=drive_link)| |
| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA Exercise](https://www.google.com/url?q=https://youtu.be/SdLFbq0lYwc&sa=D&source=editors&ust=1724832556753025&usg=AOvVaw0L-_lVsg99GtcsY1NvfzGm)| TA Khoa | [231224-23M07MC](https://drive.google.com/drive/folders/1JRSXx1G5QIPc1SLaqjfbfC0DnPrAOnZ8?usp=drive_link)| |
| <span class="badge rounded-pill bg-success">Assignment</span>| [Object Detection Project](https://drive.google.com/file/d/12_mQkl8eWTYshUWiAW39FzvzZfoDRHGi/view?usp=drive_link)| TA Hùng | Due: 31 Dec, 2023 <br/> [[solution](https://drive.google.com/file/d/1A_jf0yo1lYZvWEcubzUOLrB99fqkNrGy/view?usp=drive_link)]   | |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection (1)](https://www.google.com/url?q=https://youtu.be/1lCS9lpqcwo&sa=D&source=editors&ust=1724832556753477&usg=AOvVaw05TT_aybHs4-mc0gXGpGcD)  | Dr. Đình Vinh| [231227-23M07MC](https://drive.google.com/drive/folders/1QMpL3Zg2UcP0L-1NyEfpEH1yqT0-Z3xl?usp=drive_link)| |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection (2)](https://www.google.com/url?q=https://youtu.be/0S3NRo118pA&sa=D&source=editors&ust=1724832556753747&usg=AOvVaw1dFqs2hpS84f_q-CkDq4Lr)  | Dr. Đình Vinh| [231229-23M07MC](https://drive.google.com/drive/folders/1yTimAYEEPBEUo44xvjQA0GoMVhQs8bpt?usp=drive_link)| |
| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA Exercise](https://www.google.com/url?q=https://youtu.be/MC0g875zbZU&sa=D&source=editors&ust=1724832556754002&usg=AOvVaw2wPVT9yvyzpWcCz56yVGli)| TA Hùng | [231231-23M07MC](https://drive.google.com/drive/folders/1FVHg6pMmYkXcNJrAaf5YldaRPUWzDnjY?usp=drive_link)| |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection](https://www.google.com/url?q=https://youtu.be/BoXXy_24Lc4&sa=D&source=editors&ust=1724832556754261&usg=AOvVaw3YcTNTXecEgD89iyJ9pNlu) | Dr. Đình Vinh| [240103-23M07MC](https://drive.google.com/drive/folders/1FcvfuRDxLxL1tvnmRhIYQlrIs0yJY3xg?usp=drive_link)| |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection](https://www.google.com/url?q=https://youtu.be/vqhLNzVFPN4&sa=D&source=editors&ust=1724832556754478&usg=AOvVaw3_dqLha10ZCEje5MkjVXWk) | Dr. Đình Vinh| [240105-23M07MC](https://drive.google.com/drive/folders/1fud9bDmE_BnP_bnarc2A6HGXMwJbjv0H?usp=drive_link)| |
| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.google.com/url?q=https://youtu.be/I_4SNAs2l0w&sa=D&source=editors&ust=1724832556754724&usg=AOvVaw1CGcyQHJDsv8SJIlmX2RUS)| TA Hùng | [240107-23M07MC](https://drive.google.com/drive/folders/10uGvOnhjBzhLpub_J0Bq8nmKCW0IjJSL?usp=drive_link)| |
| <span class="badge rounded-pill bg-success">Assignment</span>| [Imbalanced Data Exercise](https://drive.google.com/file/d/1RwBdIgymEoUGDyCFIGKrYyzvYqEZfmiJ/view?usp=drive_link) | Dr. Vinh   | Due: 10 January, 2024 <br/> [[solution](https://drive.google.com/file/d/1RwBdIgymEoUGDyCFIGKrYyzvYqEZfmiJ/view?usp=drive_link)]   | |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Advanced Topic: Imbalanced Data](https://www.google.com/url?q=https://youtu.be/TXl74SdQys0&sa=D&source=editors&ust=1724832556755242&usg=AOvVaw3voqJI8kulgr0fty9gvCtr)  | Dr. Vinh| [240110-23M07MC](https://drive.google.com/drive/folders/1bxBy7VytmZdJSjTi8lzgvieWMZ9aFC73?usp=drive_link)| |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Advanced Topic: Self/semi-supervised Learning](https://www.google.com/url?q=https://youtu.be/VYcjApR35lo&sa=D&source=editors&ust=1724832556755674&usg=AOvVaw1rbuCRijlOhp3NVL5Se5du)| Dr. Hưng| [240112-23M07MC](https://drive.google.com/drive/folders/1Ectw8AOy2WujgssLdipMEDZFEUTWTsZd?usp=drive_link)| [[Exercise](https://drive.google.com/file/d/1hXaW9YzP1smmM8eIHy6QY25lz0YS_OXA/view?usp=drive_link)] - [[Solution](https://drive.google.com/file/d/1XuT_S73j9ui_2goHLYQ2DgTXJAVHbxOd/view?usp=drive_link)] |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Advanced Topic: Knowledge Distillation](https://www.google.com/url?q=https://youtu.be/nZIo5YtcwU4&sa=D&source=editors&ust=1724832556755972&usg=AOvVaw3Ahk7_yQcB548Y598ys27_) | Dr. Hưng| [240114-23M07MC](https://drive.google.com/drive/folders/1R-3KZ4oAlgeO2wFT0wsRhQsKaTDiiT2L?usp=drive_link)| [[Exercise](https://drive.google.com/file/d/1hayy7jxxRUdmd9k_pt2CN4yVU5gM4ER0/view?usp=drive_link)] - [[Solution](https://drive.google.com/file/d/1s8JHlzf1TaxnwezzAO2WU1XsOBGGt1WB/view?usp=drive_link)] |
|  <span class="badge rounded-pill bg-success">Project tutorial</span>| [Image Project: Tracking by Detection](https://www.google.com/url?q=https://youtu.be/TIZ5VBodinM&sa=D&source=editors&ust=1724832556756257&usg=AOvVaw1SQxTyBhFLR5zAoY8O0qe3)   | TA Thắng| [240117-23M07MC](https://drive.google.com/drive/folders/1DBAulIrQHF2s8neEGfe5abdvf2pOAhhB?usp=drive_link)| |
|  <span class="badge rounded-pill bg-success">Project tutorial</span>| [Image Project: Medical Image Analysis (1)](https://www.google.com/url?q=https://youtu.be/bHqXK3_0aBY&sa=D&source=editors&ust=1724832556756644&usg=AOvVaw2M5s_PG76UDtpUI9GxBi8b)   | TA Huy  | [240119-23M07MC](https://drive.google.com/drive/folders/187HKrS06ToAH84-5aDBeYDMtuOYWs6rm?usp=drive_link)|[[Exercise](https://drive.google.com/file/d/1OVb-hjNZKXUnz2awdGSl5TBzzUl-63Ch/view?usp=drive_link)] - [[Solution](https://drive.google.com/file/d/1V17sPMuKlEPqXX4x10AwAbwerKG_bPk-/view?usp=drive_link)] |
|  <span class="badge rounded-pill bg-success">Project tutorial</span>| [Image Project: Medical Image Analysis (2)](https://www.google.com/url?q=https://youtu.be/EMbMuSw8-EU&sa=D&source=editors&ust=1724832556756906&usg=AOvVaw2ziZisD133bi-pBZDvg7bd)   | TA Huy  | [240121-23M07MC](https://drive.google.com/drive/folders/1pgu1kZPkvBItE3fyNpYuYU1TiPZFoZk9?usp=drive_link)| |


## Lesson preview
| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor| <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-primary">Preview</span>| [UNet](https://www.google.com/url?q=https://youtu.be/q3HfysdFV-U&sa=D&source=editors&ust=1724832556757226&usg=AOvVaw2p0S1NWf1AoUVsA6HnxZjs)  | TA Thái | [231219-23M07-EC2](https://drive.google.com/drive/folders/1WCeKmWrz-mBJ0xxNDrlIuem8kj_Mwvpl?usp=drive_link)  | |
| <span class="badge rounded-pill bg-primary">Preview</span> | [Object Detection using Pretrained Models](https://www.google.com/url?q=https://youtu.be/2hf3t_cRc7A&sa=D&source=editors&ust=1724832556757522&usg=AOvVaw1Z0GzfqQJKdpZETBEezCx4)| TA Thái  | [231226-23M07-EC2](https://drive.google.com/drive/folders/1KPF83ydKYENEpnIWCSh6xsY7LseAKCj1?usp=drive_link)  | |
| <span class="badge rounded-pill bg-primary">Preview</span> | [Yolov1](https://www.google.com/url?q=https://youtu.be/3ABkT9mFPZU&sa=D&source=editors&ust=1724832556757744&usg=AOvVaw0M2qRU_8IWSc3hAF679kIf)|TA Thái   | [240102-23M07-EC2](https://drive.google.com/drive/folders/1xNNP62_f9s5niy34RXrxuKUJHj09HH02?usp=drive_link)  | |
| <span class="badge rounded-pill bg-primary">Preview</span> | [Introduction to Imbalanced Data](https://www.google.com/url?q=https://youtu.be/nQMrb7ySnIk&sa=D&source=editors&ust=1724832556757910&usg=AOvVaw3h4TXjckQU2nTSbF8w8oBz)  |TA Thái   | [240109-23M07-EC2](https://drive.google.com/drive/folders/1DeY9KWgWsq323bRwQQilR8E5FBv28ovc?usp=drive_link)  | |
||

## Extra Class: Research and Paper Writing

| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor| <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-info">Research & Paper</span>| [Group Report (1)](https://www.google.com/url?q=https://youtu.be/G48uhvxE4hY&sa=D&source=editors&ust=1724832556758243&usg=AOvVaw00rTYaaJOQsx8idQATEg7K) | Dr. Đình Vinh| N/A| |
| <span class="badge rounded-pill bg-info">Research & Paper</span>| [Group Report (2)](https://www.google.com/url?q=https://youtu.be/BoGSS29KXuU&sa=D&source=editors&ust=1724832556758437&usg=AOvVaw3gXuUW36v4aD0tTeEVXg-P) | Dr. Đình Vinh  | N/A| |
| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to Write a Paper (1)](https://www.google.com/url?q=https://youtu.be/Ptmf7UQMsuU&sa=D&source=editors&ust=1724832556758642&usg=AOvVaw2eSi_ZC9gBovPvKbLxVRur)|Dr. Đình Vinh   | [240106-23M07-EC1](https://drive.google.com/drive/folders/1GJ3gmt2TBVzvHD059jhtUnsCZh82sNyf?usp=drive_link)  | |
| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to Write a Paper (2)](https://www.google.com/url?q=https://youtu.be/gjjX-6QoGvo&sa=D&source=editors&ust=1724832556758904&usg=AOvVaw0AosTO3gzffzTe1LahpVyi)| Dr. Đình Vinh  | [240113-23M07-EC1](https://drive.google.com/drive/folders/1dqtr3AtNxT5rDsqwf8I6ZcXcjY8WVnGJ?usp=drive_link)  | |

## Seminars

| <i class="bi bi-bar-chart-steps"></i> Type| <i class="bi bi-journals"></i> Content   | <i class="bi bi-person"></i> Instructor| <i class="bi bi-file-earmark-text"></i> Handout  | <i class="bi bi-book"></i> Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-warning">Seminar</span>| [Advanced UNet and LLMs Introduction](https://www.google.com/url?q=https://youtu.be/bip6qL9jsZM&sa=D&source=editors&ust=1724832556759145&usg=AOvVaw3mDXVXsQzjovpxqMZPLCnP)| Dr. Vinh| [231224-23M07-EC3](https://drive.google.com/drive/folders/1LEJViWi5RWxvEwQcfd0JtAAuklvUUTIl?usp=drive_link)  | |
| <span class="badge rounded-pill bg-warning">Seminar</span>| [Multimodal Language Models](https://www.google.com/url?q=https://youtu.be/rFFXkGvzaVw&sa=D&source=editors&ust=1724832556759442&usg=AOvVaw34zm135l8ihXRwj8ooQnE1)|   | [231231-23M07-EC3](https://drive.google.com/drive/folders/1BAn4TCQSQpIEGG5-AjV9JS1Nug-wqlRz?usp=drive_link)  | |
| <span class="badge rounded-pill bg-warning">Seminar</span>| [Visual Instruction Tuning (LlaVa) and QLoRA](https://www.google.com/url?q=https://youtu.be/_Gfk1EFlOIo&sa=D&source=editors&ust=1724832556759755&usg=AOvVaw2K0iG5QBFhF3mKLii7c-SS)   |   | [240107-23M07-EC3](https://drive.google.com/drive/folders/1Cp_YloUAPoVVN2udSSLv4mZaRX8KjePx?usp=drive_link)  | |
| <span class="badge rounded-pill bg-warning">Seminar</span>| [Data Augmentation and Imbalanced Data](https://www.google.com/url?q=https://youtu.be/7PikDIQWB6c&sa=D&source=editors&ust=1724832556760026&usg=AOvVaw1CCsVBU9JbEoZ5wsPIpqUy)  |   | [240114-23M07-EC3](https://drive.google.com/drive/folders/1TrxedfyjGIft606rHU0022a7AvEM3jWi?usp=drive_link)  | |
| <span class="badge rounded-pill bg-warning">Seminar</span>| [RNN-based Forecasting and Toolformer](https://www.google.com/url?q=https://youtu.be/NkFczM4yz-A&sa=D&source=editors&ust=1724832556760277&usg=AOvVaw2blH_AYhhpf3hcg_jL-lCJ)   |   | [240121-23M07-EC3](https://drive.google.com/drive/folders/1RzFI9SuQpsS2NJVp3gR44PinZeE9WutL?usp=drive_link)  | |

# Further Readings