---
title: Module 10 - Reinforcement Learning, GNN, and LLMs
tbl-colwidths: [35,120,30,50,70]
title-block-banner: true
---

# Course Schedule and Resources

## Main lessons

| Type| Content   | Instructor     | Handout      | Further Reading   |
|-------------|------------------------------------------------------------------|----------------|--------------|--------------------------------------------|
| <span class="badge rounded-pill bg-success">Assignment</span>  | [Reinforcement Learning Exercise](https://drive.google.com/file/d/1XGn_6XpZBOPLkUDg_iODBOxwVkJxSvcM/view?usp=drive_link)     | TA Thắng| Due: 21 Apr, 2024 <br/> [[solution](https://drive.google.com/file/d/1XGn_6XpZBOPLkUDg_iODBOxwVkJxSvcM/view?usp=drive_link)]      |   |
| Preview     | [Introduction to Reinforcement Learning](https://www.google.com/url?q=https://youtu.be/67cUGpOdwjI&sa=D&source=editors&ust=1724832556757768&usg=AOvVaw1ZKGSFwGyq_pYtQjufI0k8)  | TA Thuận| [240416-23M10-EC2](https://drive.google.com/drive/folders/1BEbvm_MJJ-8-UYrRcqzNgsiZVjO_7b46?usp=drive_link) |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Reinforcement Learning (CartPole)](https://www.google.com/url?q=https://youtu.be/OgYC_dXWyc8&sa=D&source=editors&ust=1724832556758230&usg=AOvVaw26cP3G_j_j-AYw3tSn6veP)| Dr. Hoàng      | [240417-23M10-MC](https://drive.google.com/drive/folders/10PS5HhNbD-SdC0lW7Yi8eLPdjqqTZOt0?usp=drive_link) |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Reinforcement Learning (Deep Deterministic Policy Gradient)](https://www.google.com/url?q=https://youtu.be/0KOuk0VVxYo&sa=D&source=editors&ust=1724832556758621&usg=AOvVaw2C_t_jlZJEwuo0WyPqnvHs)      | Dr. Hoàng      | [240419-23M10-MC](https://drive.google.com/drive/folders/1Fo1K71u6gnhK1YTGXzTBXZbElCnxbCXq?usp=drive_link) |   |
| <span class="badge rounded-pill bg-success">Exercise Session</span>     | [TA Exercise](https://www.google.com/url?q=https://youtu.be/LWBdqHG1Hw0&sa=D&source=editors&ust=1724832556758947&usg=AOvVaw3jUsTGp48gtfP6kL6rny2T)    | TA Thắng| [240421-23M10-MC](https://drive.google.com/drive/folders/1bFlS0xLGIpZSJJ8hyK0UYXGH_xpb4IvK?usp=drive_link) |   |
| <span class="badge rounded-pill bg-success">Assignment</span>  | [Point Cloud Techniques and Applications Project](https://www.google.com/url?q=https://drive.google.com/file/d/1lFg_T25zN6mFtfVip9ZgzpQCQ_zs3Kml/view&sa=D&source=editors&ust=1724832556759379&usg=AOvVaw2nitD77Jb_ojpjlJ_15ob1) | Dr. Tuân| [[project](https://drive.google.com/file/d/1wvdTXB20LfPqdoGDbFCngo2z3BfDYRZp/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1UrfwYZX0T4ShXN15aD7JoagKU_FHARTG/view?usp=drive_link)]      |   |
| <span class="badge rounded-pill bg-success">Assignment</span>  | [Multimodal Large Language Models Exercise](https://www.google.com/url?q=https://drive.google.com/file/d/18TSBb1upiJkj3H8CxXD8MYV10LK7M1cj/view&sa=D&source=editors&ust=1724832556759677&usg=AOvVaw0EAXIP7rj04ZoIlsdXGY10)| TA Thái| Due: 27 Apr, 2024 <br/> [[solution](https://drive.google.com/file/d/1uim9UDpyXz3MCdzeRrcBUA6ut8wWyk1r/view?usp=drive_link)]     |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Classification for 3D Point Cloud Data](https://www.google.com/url?q=https://youtu.be/ebQ3e8pGSSE&sa=D&source=editors&ust=1724832556760032&usg=AOvVaw3xftg57Gb9hORBWYqSfUcI)  | Dr. Tuân| [240424-23M10-MC](https://drive.google.com/drive/folders/1p9f3MqjSh52WMEP8tRctMwbK_7H7EnGi?usp=drive_link) |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Advances in 3D Point Cloud Data](https://www.google.com/url?q=https://youtu.be/US2o866dCh8&sa=D&source=editors&ust=1724832556760424&usg=AOvVaw1wHJ2Jk2LwHAEECszJiJwu) | Dr. Tuân| [240426-23M10-MC](https://drive.google.com/drive/folders/1_c3umUx0NY89is_B4gTS2nw_JKds6sVS?usp=drive_link) |   |
| <span class="badge rounded-pill bg-success">Assignment</span>  | [Graph Neural Network Exercise](https://drive.google.com/file/d/1UjVRXIOowiloz5soQCmKSjOdLmTDMQ02/view?usp=drive_link)     | TA Đức| Due: 03 May, 2024 <br/> [[solution](https://drive.google.com/file/d/1F6H4GqApK1pBx8NzN6qM7H1A_3i7S0Kd/view?usp=drive_link)]      |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [GNN Node Classification](https://www.google.com/url?q=https://youtu.be/f1YQCJ9OfgI&sa=D&source=editors&ust=1724832556760734&usg=AOvVaw0t7NuHJBqThc1VIUxnkjKC) | Dr. Đình Vinh  | [240428-23M10-MC](https://drive.google.com/drive/folders/1S5aVka7tVVK9vdGlEsroj1o2m6s9hqzg?usp=drive_link) |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [GNN (Molecular Property Prediction)](https://www.google.com/url?q=https://youtu.be/OXxorkP-GKg&sa=D&source=editors&ust=1724832556761121&usg=AOvVaw0_05w28OfjzjKRMll9Ev5k)     | Dr. Đình Vinh  | [240501-23M10-MC](https://drive.google.com/drive/folders/1Wjc4OivDo56pt9j7oBnlVjmtpPheb2nn?usp=drive_link) |   |
| <span class="badge rounded-pill bg-success">Exercise Session</span>    | [TA Exercise](https://www.google.com/url?q=https://youtu.be/wlwqCc3kgUY&sa=D&source=editors&ust=1724832556761471&usg=AOvVaw3LCvMLSrE6z6Dy9O4GjQPv)    | TA Đức | [240503-23M10-MC](https://drive.google.com/drive/folders/1FM_1YHFEtUJjvxmMOqeqNxwupZfBOFTZ?usp=drive_link) |   |
| <span class="badge rounded-pill bg-warning">Project Tutorial</span>  | [Multitasking networks for Vision](https://www.google.com/url?q=https://youtu.be/zEEeuu6cA80&sa=D&source=editors&ust=1724832556761794&usg=AOvVaw2GHRbS3SlwvMrD4cbw4c6j)| TA Thái| [240505-23M10-MC](https://drive.google.com/drive/folders/1RSEztxAHuPcfS6DWqw7LbVn2rT1DCBiD?usp=drive_link) | [[Exercise](https://drive.google.com/file/d/1YdghVcvBqNRxBodsdM_n5R0fWCnjqiZ9/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1Z8XGSROMPyaNy9AjORkzsebjxtwJJHCz/view?usp=drive_link)]|
| <span class="badge rounded-pill bg-warning">Project Tutorial</span>  | [VideoCLIP for Video Classification](https://www.google.com/url?q=https://youtu.be/mB0nSmeDWLs&sa=D&source=editors&ust=1724832556762206&usg=AOvVaw3eA3yVr2aqPIpRpGx8YXuQ)      | TA Đức | [240508-23M10-MC](https://drive.google.com/drive/folders/18SDA8o9LI9D0v6VfQxLABc6oEz1jJ6wa?usp=drive_link) | [[handout](https://drive.google.com/file/d/1UFGQdhQZyZnpM43jji1GiZTcnlo26Llf/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/18FexSPAycsWfnw9MCAPcenPAvR6A3wBy/view?usp=drive_link)]  |
| <span class="badge rounded-pill bg-warning">Project Tutorial</span>  | [Multi-agent LLM](https://www.google.com/url?q=https://youtu.be/TPc3ZGj4vZs&sa=D&source=editors&ust=1724832556762512&usg=AOvVaw3-dK_8oIDqDk98DTijAuZW)| TA Thắng| [240510-23M10-MC](https://drive.google.com/drive/folders/1urJmD8SiAos_3S2xWxAtsWMtLKIoVsQM?usp=drive_link) | [[handout](https://drive.google.com/file/d/1SA5muWBshQtsqgxiYBwnx2U34PvDwv9A/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1x7h834-mIFEXMvodZf-Fsc6bChaYUI1U/view?usp=drive_link)]   |

## Extra class: Introduction to Large Language Models (LLMs)

| Type| Content   | Instructor     | Handout      | Further Reading   |
|-------------|------------------------------------------------------------------|----------------|--------------|--------------------------------------------|
| <span class="badge rounded-pill bg-info">Extra Class</span> | [LLM RAG for Applications](https://www.google.com/url?q=https://youtu.be/QM7_Xq6SzdE&sa=D&source=editors&ust=1724832556762972&usg=AOvVaw1l34gxUvn2cWrQhVIvNu2r)| TA Bách| [240420-23M10-MC](https://drive.google.com/drive/folders/1QeD4iEOqtPpvtntHnybq6NComjMk3uQ3?usp=drive_link) |   |
| <span class="badge rounded-pill bg-info">Extra Class</span> | [LLMs for Multimodal Data](https://www.google.com/url?q=https://youtu.be/14NHUCkTntk&sa=D&source=editors&ust=1724832556763321&usg=AOvVaw2ZozFP7k1w1U8e3tPMOQA7)| TA Thái| [240427-23M10-EC1](https://drive.google.com/drive/folders/1BTwYLzcLm8E5DKwoYxVAywXKsbONlfiO?usp=drive_link) | [Modaverse] [BLIP-2] [NExT-GPT]    |
| <span class="badge rounded-pill bg-info">Extra Class</span> | [LLM Deployment with LangChain](https://www.google.com/url?q=https://youtu.be/ndwR4byDvbQ&sa=D&source=editors&ust=1724832556763803&usg=AOvVaw06ILRVWpJDXkgCGFCXRa8k)   | TA Thắng| [240504-23M10-EC1](https://drive.google.com/drive/folders/1mJV-qgoU8knIQCZfqYs_LUMbIr10Xsaq?usp=drive_link) |