---
title: Module 8 - Applications of Deep Learning for NLP
tbl-colwidths: [35,120,30,50,70]
title-block-banner: true
---

# Course Schedule and Resources

## Main lessons

| Type  | Content   | Instructor   | Handout| Further Reading |
|-----------------------------|-----------------------------------------------------------------------------|--------------|-------------------|-----------------|
| Preview          | [Introduction to POS Tagging](https://www.google.com/url?q=https://youtu.be/B3uINL6U25c&sa=D&source=editors&ust=1724832556752652&usg=AOvVaw1a_jF9fm_jJ2DNaBUG05MI)     | TA Khoa      | [240130-23M08-EC2](https://drive.google.com/drive/folders/1b5Xxz3btiTpIFZyLHnmbG19N9YJVwvBK?usp=drive_link)  |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span> | [From Text Classification to POS Tagging](https://www.google.com/url?q=https://youtu.be/4TSRPGbgU8E&sa=D&source=editors&ust=1724832556753082&usg=AOvVaw0oCk8Bc_2ZG-zgsqaSuZJu)    | Dr. Vinh     | [240131-23M08MC](https://drive.google.com/drive/folders/1GmaVb_YYT5EuA543F3OL6B-7-l5O2y2X?usp=drive_link)    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span> | [NER for Medical Data](https://www.google.com/url?q=https://youtu.be/Wm3Zun-AL8s&sa=D&source=editors&ust=1724832556753491&usg=AOvVaw2w3jc68F8tbWQgbjzjBfbp) | Dr. Vinh     | [240202-23M08MC](https://drive.google.com/drive/folders/1fSoKLb7UckQhs7wSAybWu1LLexFKnyZ7?usp=drive_link)    |      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>       | [TA-Exercise](https://www.google.com/url?q=https://youtu.be/wig6pC03o8I&sa=D&source=editors&ust=1724832556753921&usg=AOvVaw2Vm3mcxtw1aNndNgpDvOlq)          | TA Thái      | [240204-23M08MC]()    |      |
| <span class="badge rounded-pill bg-primary">Project handout</span>| Aspect-based Sentiment Analysis Project |TA Thái      | Due: 06 Feb, 2024 <br/> [[solution](https://drive.google.com/file/d/1gJGeBVuFY1h6dQod9tZPIEEr6fqDKhix/view?usp=drive_link)]    |      |
| <span class="badge rounded-pill bg-success">Project tutorial</span> | [Text Project: Aspect Extraction and Content Classification (Text Classification + NER)](https://www.google.com/url?q=https://youtu.be/aZX31G8JYTQ&sa=D&source=editors&ust=1724832556754658&usg=AOvVaw0lV5FFQC47nGR8E7ZPQb9c) | TA Thái      | [240206-23M08MC](https://drive.google.com/file/d/1JhgLUZSW8nCbuzpG4conbqdeVR703GFW/view?usp=drive_link)    |      |
| <span class="badge rounded-pill bg-success">Project tutorial</span> | [Text Project: QA for Content Inquiry (Text Classification + NER)](https://www.google.com/url?q=https://youtu.be/igo1Gcsskmo&sa=D&source=editors&ust=1724832556755059&usg=AOvVaw1UxLbQV0dgRL6mFK2HuYfn) | TA Thắng     | [240216-23M08MC](https://drive.google.com/drive/folders/1H6Ui_ZbWOSWJVv-TOywlOavXBS_5OF6t?usp=drive_link)    |      |
| <span class="badge rounded-pill bg-success">Project tutorial</span> | [Text Project: End-to-end Question Answering (Building a Searching System)](https://www.google.com/url?q=https://youtu.be/-o_xEU0142s&sa=D&source=editors&ust=1724832556755463&usg=AOvVaw3lU663uBCjLF8mb_WKO0UN)   | TA Thắng     | [240218-23M08MC](https://drive.google.com/drive/folders/1dcPKUp1O4ZhTSuno06m_8Q5xCd1KGelq?usp=drive_link)    | [[Exercise](https://drive.google.com/file/d/1nfRCQ01AEG_wyL1PyUdcO2aDw36JWwwb/view?usp=drive_link)] - [[Solution](https://drive.google.com/file/d/1FbbdrWPu1Jndbr6CLMIip1O5aIv35Ddo/view?usp=drive_link)]      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Text Generation](https://www.google.com/url?q=https://youtu.be/WHUHvUZoAu0&sa=D&source=editors&ust=1724832556755867&usg=AOvVaw3WL_W7WkaAYnL0caWp48aD)      | Dr. Vinh     | [240221-23M08MC](https://drive.google.com/drive/folders/1_Iszx-jhBj9afDqv3EJDsH0HTiGVaODl?usp=drive_link)    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Machine Translation](https://www.google.com/url?q=https://youtu.be/SKxjf_xCUco&sa=D&source=editors&ust=1724832556756261&usg=AOvVaw3EWyOyuZgvfTfZ0NACnSkZ)  | Dr. Vinh     | [240223-23M08MC](https://drive.google.com/drive/folders/1WUVuBokSJKDMXhzp_4zBp_xplR0QMTxP?usp=drive_link)    |      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>       | [TA Exercise (Neural Machine Translation)](https://www.google.com/url?q=https://youtu.be/YoJaVEWFu5s&sa=D&source=editors&ust=1724832556756660&usg=AOvVaw1bt3nn0zBwgzL5FBx-WD9E)   | TA Thái      | 240225-23M08MC    |      |
| <span class="badge rounded-pill bg-primary">Project handout</span>|[Neural Machine Translation](https://drive.google.com/file/d/1iwcGmteLgiHK6bjPrkeHESJ0Ou72pog_/view?usp=drive_link)      | TA Thái      |Due: 25 Feb, 2024 <br/> [[Solution](https://drive.google.com/file/d/109WVkM1VjJ4KPk3i8jSMghVfn-EvJC4S/view?usp=drive_link)]|      |
| <span class="badge rounded-pill bg-success">Project tutorial</span> | [Poem Generation Project](https://www.google.com/url?q=https://drive.google.com/file/d/1xbsKZ4D2D-IotpGS3UH4PLYI7NGbb2XR/view&sa=D&source=editors&ust=1724832556757447&usg=AOvVaw3bjeHwHmWvaUatReLuT4YM)         | TA Thắng     | [240228-23M08MC](https://drive.google.com/drive/folders/1Lq67LkhT2ttVMi3199-k7mjALCD7Cucl?usp=drive_link)    | [[handout](https://drive.google.com/file/d/1rGBYnGJ4hum3_Wsqhb_lsKQkou5jUiaA/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/19clunVS32mKVMQZ1grSdh1oNiiGJ-ZXB/view?usp=drive_link)]      |
| <span class="badge rounded-pill bg-success">Project tutorial</span> | [Low-resource Machine Translation Project](https://www.google.com/url?q=https://drive.google.com/file/d/1y54kDnjqkc7n9gWYQmoRK3k-Bg3yHP9_/view&sa=D&source=editors&ust=1724832556757842&usg=AOvVaw346CP7hgSd26KDK8yzsLu3)   | TA Thái      | [240301-23M08MC](https://drive.google.com/drive/folders/11KuB6GI2GnPKpdiSN2n3LWQYCym8gCmw?usp=drive_link)    | [[handout](https://drive.google.com/file/d/1Ak7U0Il1hZ526khNK89x2OWeJtNLXD8v/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1szQ2EQfJZSr4UZnFlQBgTRJ95De4MUR1/view?usp=drive_link)]      |
| <span class="badge rounded-pill bg-success">Project tutorial</span> | [Text classification with Mamba Project](https://www.google.com/url?q=https://drive.google.com/file/d/1slYK6jHlGKnXyEAAAOrFx0J3oe8iC_p_/view&sa=D&source=editors&ust=1724832556758394&usg=AOvVaw2nQEhtFT1E4gPibqyIr0YF)     | TA Đức       | [240303-23M08MC](https://drive.google.com/drive/folders/1p26eq3_VbXoreexdeNDkoqUsyGgFuLwT?usp=drive_link)        | [[handout](https://drive.google.com/file/d/1OAEbXu2KZanmQsmne3C1ufoFtpwOFQTT/view?usp=drive_link)] - [[solution](https://drive.google.com/file/d/1QREsQeGnPu_lzthdMbslkc_Sc_RIEnYG/view?usp=drive_link)]      |


## Extra class: Research and Paper Writing

| Type  | Content   | Instructor   | Handout| Further Reading |
|-----------------------------|-----------------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-info">Research & Paper</span>          | [How to write a paper (3)](https://www.google.com/url?q=https://youtu.be/0ozStzOZJZA&sa=D&source=editors&ust=1724832556759573&usg=AOvVaw3TN4jItpvigiFP7F0SRrjd)        | Dr. Đình Vinh| [240127-23M08-EC1](https://drive.google.com/drive/folders/1Dd9v8dMLL4dorDioAKVibY-RbK5YVIMs?usp=drive_link)  |      |
| <span class="badge rounded-pill bg-info">Research & Paper</span>          | [How to write a paper (4)](https://www.google.com/url?q=https://youtu.be/tg_TQPDMKa0&sa=D&source=editors&ust=1724832556759993&usg=AOvVaw3J7OLTwzpNeLDEqCDgUaA2)        | Dr. Đình Vinh| [240203-23M08-EC1](https://drive.google.com/drive/folders/1GPN288V7BBUsO_Cpe9vLlX05d9pG5fra?usp=drive_link)  |      |

## Extra class: MLOps

| Type  | Content   | Instructor   | Handout| Further Reading |
|-----------------------------|-----------------------------------------------------------------------------|--------------|-------------------|-----------------|
| MLOps | [Model Quantization](https://www.google.com/url?q=https://youtu.be/-UENe8cARMQ&sa=D&source=editors&ust=1724832556760446&usg=AOvVaw28IUT8hC3R-Z76kK4YtxlM)   | TA Bách      | [240302-23M09-EC1](https://drive.google.com/drive/folders/19K_raciKlh8BU0Ig5aNWAqVVMIQ0NJAr?usp=drive_link)  |      |

## Seminar

| Type  | Content   | Instructor   | Handout| Further Reading |
|-----------------------------|-----------------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-warning">Seminar</span>          | [CLIP](https://www.google.com/url?q=https://youtu.be/6xCgzkkx7So&sa=D&source=editors&ust=1724832556760901&usg=AOvVaw2rOBVEG93Doqe7kbFtSbcn)      | TA Đức       | 240128-23M08-EC3  |      |
| <span class="badge rounded-pill bg-warning">Seminar</span>          | [Detecting violation of helmet rule for motorcyclists (CVPRW2024)](https://www.google.com/url?q=https://youtu.be/kERiVxH_N-0&sa=D&source=editors&ust=1724832556761288&usg=AOvVaw3dyQeA_PRj8QIoKyuWUPhT) | Dr. Vinh     | [240204-23M08-EC3](https://drive.google.com/drive/folders/1Z6oO5mUSIMBsJ7-8TVou519VyDBzTtI8?usp=drive_link)  |      |
| <span class="badge rounded-pill bg-warning">Seminar</span>          | [Direct Preference Optimization](https://www.google.com/url?q=https://youtu.be/trhYxMQG47A&sa=D&source=editors&ust=1724832556761683&usg=AOvVaw2d1N5WbqKz0IVcOmdiSqIA)  | Dr. Vinh     | [240224-23M08-EC3](https://drive.google.com/drive/folders/1mi1qEzGIkbCwqyf2frARqkQ0d5v2BqIC?usp=drive_link)  |      |
| <span class="badge rounded-pill bg-warning">Seminar</span>          | [Study and Job in the USA](https://www.google.com/url?q=https://youtu.be/tY7OKXm6ApA&sa=D&source=editors&ust=1724832556762072&usg=AOvVaw1MDq7OHQXdU80gsE8Uf2kL)          |   |        |      |

## Extra class: Introduction to Large Language Models (LLMs)

| Type  | Content   | Instructor   | Handout| Further Reading |
|-----------------------------|-----------------------------------------------------------------------------|--------------|-------------------|-----------------|
| LLMs  | [Introduction to Text Generation](https://www.google.com/url?q=https://youtu.be/ShhDaN_Z6Es&sa=D&source=editors&ust=1724832556762440&usg=AOvVaw39HN684y0wA0IwLu5v_DT3) | Dr. Vinh     | [240220-23M08-EC2](https://drive.google.com/drive/folders/1Kn4o8edOayZt0tsFHReRkN2UclQ90Tew?usp=drive_link)  |      |
