project:
  type: website

website:
  title: "AI Training"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Lectures"
        menu:
          - href: module1.qmd
            text: Module 1 | Introduction to Python Programming
          - href: module2.qmd
            text: Module 2 | Mathematical background for AI
          - href: module3.qmd
            text: Module 3 | 
          - href: module4.qmd
            text: Module 4
          - href: module5.qmd
            text: Module 5
          - href: module6.qmd
            text: Module 6
          - href: module7.qmd
            text: Module 7
          - href: module8.qmd
            text: Module 8
          - href: module9.qmd
            text: Module 9
          - href: module10.qmd
            text: Module 10

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




