project:
  type: website

website:
  title: "AIO Course"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  search:
    location: navbar
    type: overlay
  navbar:
    background: '#687a96'
    foreground: "#f5f6f7"
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Lectures"
        menu:
          - href: module1.qmd
            text: Module 1 | Introduction to Python Programming
          - href: module2.qmd
            text: Module 2 | Calculus and Linear Algebra for AI
          - href: module3.qmd
            text: Module 3 | 
          - href: module4.qmd
            text: Module 4
          - href: module5.qmd
            text: Module 5
          - href: module6.qmd
            text: Module 6
          - href: module7.qmd
            text: Module 7
          - href: module8.qmd
            text: Module 8
          - href: module9.qmd
            text: Module 9
          - href: module10.qmd
            text: Module 10
      - href: resources/resources.qmd
        text: Resources
      - href: misc/misc.qmd
        text: Misc
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: false
  page-footer: 
    ' "*(AI) will rank among our greatest technological achievements, and everyone deserves to play a role in shaping it*". — Fei-Fei Li' 
  sidebar:
    style: "docked"
    border: false
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Course content"
        contents:
          - href: module1.qmd
            text: Module 1
          - href: module2.qmd
            text: Module 2
          - href: module3.qmd
            text: Module 3
          - href: module4.qmd
            text: Module 4
          - href: module5.qmd
            text: Module 5
          - href: module6.qmd
            text: Module 6
          - href: module7.qmd
            text: Module 7
          - href: module8.qmd
            text: Module 8
          - href: module9.qmd
            text: Module 9
          - href: module10.qmd
            text: Module 10
      - section: "Others"
        contents:
          - text: Resources
            href: resources/resources.qmd
          - text: Misc 
            href: misc/misc.qmd
      
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 220px
      body-width: 1000px
      margin-width: 220px
      gutter-width: 1.4rem




