project:
  type: website
  output-dir: docs

website:
  title: "AIO Course"
  favicon: logo.png
  bread-crumbs: false
  search:
    location: navbar
    type: textbox
  navbar:
    background: '#434445'
    search: true
    left:
      - href: blogs/index.qmd
        text: Blog
      - href: academia/index.qmd
        text: Academia
      - href: faq.qmd
        text: FAQ
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
  - id: ml-glossary
    style: "docked"
    search: true
    border: true
    pinned: true
    title: "ML Glossary"
    contents:
    - section: "Information Theory"
      contents:
          - text: Entropy
            href: ml-glossary/entropy.qmd
    - href: ml-glossary/contrastive-learning/contrastive-learning.qmd
      text: Contrastive Learning
    - href: ml-glossary/contrastive-learning/triplet-loss.qmd
      text: Triplet Loss
    
    
  - id: main
    style: "docked"
    contents:
      - text: "Introduction"
        href: index.qmd
format:
  html:
    include-before-body: assets/bar.html
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    smooth-scroll: true
    fontsize: 1em
    linkcolor: "#3b9ced"
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 220px
      gutter-width: 1.4rem


