project:
  type: website
  output-dir: docs

website:
  title: "AIO Course"
  favicon: logo.png
  bread-crumbs: false
  search:
    location: navbar
    type: textbox
  navbar:
    background: '#434445'
    search: true
    pinned: true
    left:
      - icon: bi-gear
        href: mlops/index.qmd
        text: MLOps
      - icon: bi-journal-text
        href: blogs/index.qmd
        text: Blog
      - icon: bi-mortarboard
        href: academia/index.qmd
        text: Academia
      - icon: bi-collection
        text: "Stanford Courses"
        menu:
          - icon: bi-book-half
            href: stanford/cs336/cs336.qmd
            text: CS336 Language Modeling From Scratch
      - icon: bi-question-circle
        href: faq.qmd
        text: FAQ
    right:
      - icon: bi-sun-fill
        id: theme-toggle

  back-to-top-navigation: true
  page-navigation: true
  # sidebar:
  # - id: ml-glossary
  #   style: "docked"
  #   search: true
  #   border: true
  #   pinned: true
  #   title: "ML Glossary"
  #   contents:
  #   - section: "Information Theory"
  #     contents:
  #         - text: Entropy
  #           href: ml-glossary/entropy.qmd
  #   - href: ml-glossary/contrastive-learning/contrastive-learning.qmd
  #     text: Contrastive Learning
  #   - href: ml-glossary/contrastive-learning/triplet-loss.qmd
  #     text: Triplet Loss
    
    
  # - id: main
  #   style: "docked"
  #   contents:
  #     - text: "Introduction"
  #       href: index.qmd
format:
  html:
    include-before-body: assets/bar.html
    include-after-body: _includes/chatbot.html
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    theme: [flatly, theme.scss]
    respect-user-color-scheme: false
    css: styles.css
    toc: true
    smooth-scroll: true
    fontsize: 1em
    linkcolor: "#3b9ced"
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 220px
      gutter-width: 1.4rem


