project:
  type: website

website:
  title: "AIO Course"
  favicon: logo.png
  bread-crumbs: false
  search:
    location: navbar
    type: textbox
  navbar:
    background: '#434445'
    search: true
    left:
      - text: "Lectures"
        menu:
          - href: modules/module1.qmd
            text: Module 1 | Introduction to Python Programming
          - href: modules/module2.qmd
            text: Module 2 | Calculus and Linear Algebra for AI
          - href: modules/module3.qmd
            text: Module 3 | Probability and Statistics for AI
          - href: modules/module4.qmd
            text: Module 4 | Machine Learning and Data Science
          - href: modules/module5.qmd
            text: Module 5 | Deep Learning Prerequisites
          - href: modules/module6.qmd
            text: Module 6 | Introduction to Deep Learning
          - href: modules/module7.qmd
            text: Module 7 | Advanced Model Architectures for Computer Vision
          - href: modules/module8.qmd
            text: Module 8 | Applications of Deep Learning for NLP
          - href: modules/module9.qmd
            text: Module 9 | Generative Models
          - href: modules/module10.qmd
            text: Module 10 | Reinforcement Learning, GNN, and LLMs
      - text: Resources      
        menu:
          - href: resources/research/research.qmd
            text: Research and Paper Writing
          - href: resources/repo.qmd
            text: GitHub Repository
          - href: resources/grad-life/grad-life.qmd
            text: Graduate life
          - href: resources/books.qmd
            text: Books
          - href: resources/courses.qmd
            text: Courses
          - href: resources/papers.qmd
            text: Fundamental Papers
          - href: resources/talks.qmd
            text: Talks
      - href: blogs/blogs.qmd
        text: Blogs
      - href: news/ainews.qmd
        text: AI News
      - href: seminars.qmd
        text: Seminars
      - href: ml-glossary/ml-glossary.qmd
        text: ML Glossary
      - href: memes/memes.qmd
        text: Memes
  back-to-top-navigation: true
  page-navigation: true
  page-footer: 
    ' "*(AI) will rank among our greatest technological achievements,
     and everyone deserves to play a role in shaping it*". — Fei-Fei Li' 
  sidebar:
  - id: ml-glossary
    style: "docked"
    search: true
    border: true
    pinned: true
    title: "ML Glossary"
    contents:
    - section: "Information Theory"
      contents:
          - text: Entropy
            href: ml-glossary/entropy.qmd
    - href: ml-glossary/contrastive-learning/contrastive-learning.qmd
      text: Contrastive Learning
    - href: ml-glossary/contrastive-learning/triplet-loss.qmd
      text: Triplet Loss
    
    
  - id: main
    style: "docked"
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Course content"
        contents:
          - href: modules/module1.qmd
            text: Module 1
          - href: modules/module2.qmd
            text: Module 2
          - href: modules/module3.qmd
            text: Module 3
          - href: modules/module4.qmd
            text: Module 4
          - href: modules/module5.qmd
            text: Module 5
          - href: modules/module6.qmd
            text: Module 6
          - href: modules/module7.qmd
            text: Module 7
          - href: modules/module8.qmd
            text: Module 8
          - href: modules/module9.qmd
            text: Module 9
          - href: modules/module10.qmd
            text: Module 10
      - section: "Others"
        contents:
          - text: Resources
            href: resources/resources.qmd
          - text: Blogs 
            href: blogs/blogs.qmd
          - href: ainews.qmd
            text: AI News
          - href: seminars.qmd
            text: Seminars
          - href: ml-glossary/ml-glossary.qmd
            text: ML Glossary
          - href: memes.qmd
            text: Memes
    sidebar-nav-files-sidebar: custom
    sidebar-nav-files-sidebar-custom: |
      if (path.startsWith('ml-glossary')) {
        return 'ml-glossary';
      } else {
        return 'main';
      }
language:
  search-box-placeholder: Search this website
format:
  html:
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css">
    theme:
      light: [flatly, custom-theme.scss]
    css: styles.css
    toc: true
    smooth-scroll: true
    fontsize: 1em
    linkcolor: "#3b9ced"
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 220px
      gutter-width: 1.4rem


