project:
  type: website

website:
  title: "AIO Course"
  bread-crumbs: false
  search:
    location: navbar
    type: textbox
  navbar:
    background: '#434445'
    search: true
    left:
      - text: "Lectures"
        menu:
          - href: module1.qmd
            text: Module 1 | Introduction to Python Programming
          - href: module2.qmd
            text: Module 2 | Calculus and Linear Algebra for AI
          - href: module3.qmd
            text: Module 3 | Probability and Statistics for AI
          - href: module4.qmd
            text: Module 4 | Machine Learning and Data Science
          - href: module5.qmd
            text: Module 5 | Deep Learning Prerequisites
          - href: module6.qmd
            text: Module 6 | Introduction to Deep Learning
          - href: module7.qmd
            text: Module 7 | Advanced Model Architectures for Computer Vision
          - href: module8.qmd
            text: Module 8 | Applications of Deep Learning for NLP
          - href: module9.qmd
            text: Module 9 | Generative Models
          - href: module10.qmd
            text: Module 10 | Reinforcement Learning, GNN, and LLMs
      - href: resources/resources.qmd
        text: Resources
      - href: misc/misc.qmd
        text: Misc
      - href: ainews.qmd
        text: AI News
      - href: seminars.qmd
        text: Seminars
      - href: memes.qmd
        text: Memes
  back-to-top-navigation: true
  page-navigation: true
  page-footer: 
    ' "*(AI) will rank among our greatest technological achievements, and everyone deserves to play a role in shaping it*". — Fei-Fei Li' 
  sidebar:
    style: "docked"
    border: false
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Course content"
        contents:
          - href: module1.qmd
            text: Module 1
          - href: module2.qmd
            text: Module 2
          - href: module3.qmd
            text: Module 3
          - href: module4.qmd
            text: Module 4
          - href: module5.qmd
            text: Module 5
          - href: module6.qmd
            text: Module 6
          - href: module7.qmd
            text: Module 7
          - href: module8.qmd
            text: Module 8
          - href: module9.qmd
            text: Module 9
          - href: module10.qmd
            text: Module 10
      - section: "Others"
        contents:
          - text: Resources
            href: resources/resources.qmd
          - text: Misc 
            href: misc/misc.qmd
language:
  search-box-placeholder: Search this website
format:
  html:
    theme:
      light: [flatly, custom-theme.scss]
      dark: [darkly, custom-theme.scss]
    css: styles.css
    toc: true
    linkcolor: "#3b9ced"
    fontsize: 0.85em
    grid:
      sidebar-width: 220px
      body-width: 1000px
      margin-width: 220px
      gutter-width: 1.4rem



