---
title: Module 6 - Introduction to Deep Learning
tbl-colwidths: [25,35,105,40,40,70]
css: styles.css
format:
  html:
    grid:
      body-width: 1000px
    smooth-scroll: true
    fontsize: 0.85em
title-block-banner: true
---

# Course schedule and Material

## Main lessons
| Date       | Type  | Content          | Instructor   | Handout  | Further Reading  |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|
| 06/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| Convolutional Neural Network Exercise  | TA Thái      | [solution] |       |
| 08/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic CNN (1)](https://www.youtube.com/watch?v=6pC_uYiwb1s)    | Dr. Vinh     | 231108   | [CS231N Note] [CNN Explainer]          |
| 10/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic CNN (2)](https://www.youtube.com/watch?v=K2h27Nd9cFc)    | Dr. Vinh     | 231110   |       |
| 12/11/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.youtube.com/watch?v=FojbBIDACD8)      | TA Thắng     | 231112   |       |
| 13/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| Convolutional Neural Network Exercise  | TA Thắng     | [solution] |       |
| 15/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [CNN Training](https://www.youtube.com/watch?v=WScW5CWOagE)     | Dr. Vinh     | 231115   | [VGG Paper]      |
| 17/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [CNN Generalization](https://www.youtube.com/watch?v=Tcdw6E8Q_as)          | Dr. Vinh     | 231117   |       |
| 19/11/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://youtu.be/ZZ67uJBQKJI)      | TA Thắng     | 231119   |       |
| 20/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| Pretrained Models for Image Exercise   | TA Thắng     | [solution] |       |
| 22/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Advanced CNN Architecture](https://www.youtube.com/watch?v=GFMbC1HdMsM)   | Dr. Vinh     | 231122   |       |
| 24/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Transfer Learning for CNN](https://www.youtube.com/watch?v=xPdmbOfzqNA)   | Dr. Vinh     | 231124   |       |
| 26/11/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.youtube.com/watch?v=9naw1lJrKl4)      | TA Thái      | 231126   |       |
| 27/11/23| <span class="badge rounded-pill bg-success">Assignment</span>| Recurrent Neural Network Exercise      | TA Thắng     |          |       |
| 29/11/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic RNN/LSTM (Time series and Text)](https://www.youtube.com/watch?v=jH3h_FrncU8)  | Dr. Vinh     | 231129   |       |
| 01/12/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Basic RNN/LSTM (Time series and Text)](https://www.youtube.com/watch?v=b3dVz7d7Qt0)  | Dr. Vinh     | 231201   |       |
| 03/12/23| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.youtube.com/watch?v=N05jwQLMdyc)      | TA Thắng     | 231203   |       |
| 04/12/23| <span class="badge rounded-pill bg-success">Assignment</span>| Transformer Application Exercise       |   |          |       |
| 06/12/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Transformer (Encoder - Text Classification)](https://www.youtube.com/watch?v=V_WnoOvYxMQ)       | Dr. Vinh     | 231206   | BERT Readings    |
| 08/12/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Transformer for Image and Time series Data](https://www.youtube.com/watch?v=Sql8bAPGI_U)        | Dr. Vinh     | 231208   |       |
| 13/12/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Image Project: OCR with YOLOv8 and CNN (Scene Text Recognition)](https://www.youtube.com/watch?v=SnYz7k5fRwM) | TA Thắng     | 231213   |       |
| 15/12/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Image-text Project: VQA](https://www.youtube.com/watch?v=FKCr83VpQ4w)     | TA Thắng     | 231215   |       |
| 17/12/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Time-series forecasting project](https://www.youtube.com/watch?v=3jxk1udOBik)        | Dr. Đình Vinh| 231217   |       |

## Competition Training

| Date       | Type  | Content          | Instructor   | Handout  | Further Reading  |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|
| 09/11/23| <span class="badge rounded-pill bg-warning">Competition</span>| [Zalo AI](https://www.youtube.com/watch?v=sEbWP2JmUtM)          | TA Hùng      | 231109   |       |
| 16/11/23| <span class="badge rounded-pill bg-warning">Competition</span>| [Zalo AI](https://www.youtube.com/watch?v=VJpZBriXPog)          |   | 231116   |       |

## Python Review
| Date       | Type  | Content          | Instructor   | Handout  | Further Reading  |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|       
| 07/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Introduction to CNN](https://www.youtube.com/watch?v=R2z38h40sGI)         | TA Thái      | 231107   |       |
| 14/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Advanced CNN](https://www.youtube.com/watch?v=hgDSSIT5xdo)     |   | 231114   |       |
| 21/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [CNN and its variants](https://www.youtube.com/watch?v=iF0bjYTA20E)        |   | 231121   |       |
| 28/11/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Introduction to Transfer Learning](https://www.youtube.com/watch?v=WzbPAPAs1r4)      |   | 231128   |       |
| 05/12/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Introduction to Transformer](https://www.youtube.com/watch?v=m-nTyZ8AH1U) |   | 231205   | Generative AI exists because of the transformer |


## Extra class: Research & Paper Writing
| Date       | Type  | Content          | Instructor   | Handout  | Further Reading  |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|        
| 11/11/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [Research Idea - Brainstorming (1)](https://www.youtube.com/watch?v=txoSTaozyMM)      | Dr. Đình Vinh| 231111   |       |
| 18/11/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [Research Idea - Brainstorming (2)](https://www.youtube.com/watch?v=wNcnxaTTckc)      |   | 231118   |       |
| 25/11/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to do Research (1)](https://www.youtube.com/watch?v=iDILV4nI3tM)      |   | 231125   |       |
| 02/12/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to do Research (2)](https://www.youtube.com/watch?v=f4J1pHjQNdU)      |   | 231202   |       |
| 09/12/23| <span class="badge rounded-pill bg-info">Research & Paper</span>| [How to do Research (3)](https://www.youtube.com/watch?v=zzOKcKvPx-0)      |   | 231209   |       |
|

## Seminar
| Date       | Type  | Content          | Instructor   | Handout  | Further Reading  |
|------------|-----------------------------|--------------------------------------------------------------|--------------|----------|----------------------------------------|  
| 10/12/23| <span class="badge rounded-pill bg-info">Seminar</span> | [Transformers for Time series data](https://www.youtube.com/watch?v=Y-KDJZq1skI)      | Dr. Vinh     | 231210-1 |       |
| 17/12/23| <span class="badge rounded-pill bg-info">Seminar</span> | [Scholarship and Feature Extraction in Time Series Data](https://www.youtube.com/watch?v=SHIYAz0uLzw)       |   |          |       |
