---
title: Module 9 - Generative Models
tbl-colwidths: [35,120,30,50,70]
css: styles.css
format:
  html:
    grid:
      body-width: 1000px
    smooth-scroll: true
    fontsize: 0.85em
title-block-banner: true
---

# Course Schedule and Resources

## Main lessons

| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| **<span class="badge rounded-pill bg-primary">Main Lesson</span> ** ||       |     |      |
| <span class="badge rounded-pill bg-success">Assignment</span>    | Style Transfer Exercise     | TA Khoa          |     |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Basic Style Transfer](https://www.google.com/url?q=https://youtu.be/YktF-L5Y4eE&sa=D&source=editors&ust=1724832556756434&usg=AOvVaw0PO2w8W5IMVUiqK719sVNa)       | Dr. Vinh         | 240306-23M09-MC|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Multimodal Style Transfer](https://www.google.com/url?q=https://youtu.be/NYYZi3y_GcU&sa=D&source=editors&ust=1724832556756743&usg=AOvVaw1o0959BFb5Of-7TFiY650x)   | Dr. Vinh         | 240308-23M09-MC|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [TA Exercise](https://www.google.com/url?q=https://youtu.be/fmWOQo_ru2c&sa=D&source=editors&ust=1724832556757041&usg=AOvVaw1URvhQeOMpbB9MxvRDalxd)  | TA Khoa          | 240310-23M09-MC|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [TA Exercise](https://www.google.com/url?q=https://youtu.be/TNDtPtHz7Wo&sa=D&source=editors&ust=1724832556757323&usg=AOvVaw1ogn1fod5EboUIyGGWrwYl)  | TA Thái          | 240317-23M09-MC|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [GAN and DCGAN](https://www.google.com/url?q=https://youtu.be/Lpj4j8Vw_H8&sa=D&source=editors&ust=1724832556757650&usg=AOvVaw24V7DSybYICOi_4vFFu6mE)    | Dr. Vinh         | 240320-23M09-MC|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Pix2Pix and CycleGAN](https://www.google.com/url?q=https://youtu.be/eEMzZKA8suw&sa=D&source=editors&ust=1724832556757958&usg=AOvVaw23eULYRNbrwPASwIj9kwlT)        | Dr. Vinh         | 240322-23M09-MC|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [Text to Image Synthesis with DCGAN](https://www.google.com/url?q=https://youtu.be/rAsKchlROVY&sa=D&source=editors&ust=1724832556758245&usg=AOvVaw2aActh47cOnEGU5sGpQKjn) | TA Thái          | 240324-23M09-MC|      |
| <span class="badge rounded-pill bg-success">Assignment</span>    | [Image Inpainting with DDPMs](https://www.google.com/url?q=https://drive.google.com/file/d/137VozceS2H8V2tR1QOJDaTJ0b8SrXsxN/view?usp%3Ddrivesdk&sa=D&source=editors&ust=1724832556758541&usg=AOvVaw2EZUSnpWAYCeDtGC-ZY4-J)  | TA Thái          | [solution]     |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Diffusion Models (1)](https://www.google.com/url?q=https://youtu.be/e_TYyoBkHus&sa=D&source=editors&ust=1724832556758835&usg=AOvVaw3nEMxpJNeaIcuPd3g0bklT)         | Dr. Đình Vinh    | 240327-23M09-MC| Tutorial on Diffusion Models for Imaging and Vision |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Diffusion Models (2)](https://www.google.com/url?q=https://youtu.be/3ucd3fsVaIk&sa=D&source=editors&ust=1724832556759188&usg=AOvVaw3p0D2QLqOy6VYhSDryy79Q)         | Dr. Đình Vinh    | 240329-23M09-MC|      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>  | [Diffusion-based Image Inpainting](https://www.google.com/url?q=https://youtu.be/9Y_sRfsEKdI&sa=D&source=editors&ust=1724832556759475&usg=AOvVaw0rtuVfY3ZpOAHoNi3ryDl2)   | TA Thái          | 240331-23M09-MC|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Project: VAE-based Image Colorization](https://www.google.com/url?q=https://youtu.be/aZVRG_ybkr0&sa=D&source=editors&ust=1724832556759762&usg=AOvVaw0IWhKLQO5Uc6qvg8ooyinJ)  | Dr. Tài          | 240403-23M09-MC|      |
| Project tutorial - PT | [Project: Diffusion-based Image Colorization](https://www.google.com/url?q=https://youtu.be/EniYKDr10mg&sa=D&source=editors&ust=1724832556760062&usg=AOvVaw0LazRuYOc7sIcWwT5Sh_TX)    | Dr. Tài          | 240407-23M09-MC|      |
| <span class="badge rounded-pill bg-success">Assignment</span>    | Text to Image Synthesis with Stable Diffusion (and CLIP) | TA Thái          |     |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Stable Diffusion](https://www.google.com/url?q=https://youtu.be/y4P7JDgKCvU&sa=D&source=editors&ust=1724832556760562&usg=AOvVaw37RV_Bp8RVueNm7TrTZDvZ)  | Dr. Đình Vinh    | 240410-23M09-MC|      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>   | [Introduction to OpenAI's Sora](https://www.google.com/url?q=https://youtu.be/4aDFyY8dAkI&sa=D&source=editors&ust=1724832556760868&usg=AOvVaw2jmMs7nqKsxzTz8HfjNhYT)          | Dr. Đình Vinh    | 240412-23M09-MC|      |
| Project tutorial - PT | [Text to Image Synthesis with Stable Diffusion (and CLIP)](https://www.google.com/url?q=https://youtu.be/5JPrVLhkQjo&sa=D&source=editors&ust=1724832556761158&usg=AOvVaw0KHPXkgADVKvAnDVDkuNwb) | TA Thái  | 240414-23M09-MC|      |


##  Extra class: Introduction to Large Language Models (LLMs)
| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| LLMs          | [Training a minChatGPT](https://www.google.com/url?q=https://youtu.be/kEzLMnpw5zE&sa=D&source=editors&ust=1724832556761518&usg=AOvVaw0xX0tfQ4TMfKqRPXPVSXk1)        | TA Thái          | 240406-23M10-EC1          |      |
| LLMs          | [LLM Finetuning for Math Solver](https://www.google.com/url?q=https://youtu.be/pB2gb7e_N18&sa=D&source=editors&ust=1724832556761827&usg=AOvVaw1kyLx6mvb9-nK__-Kwzu7h)          | TA Thắng         | 240413-23M10-EC1          |      |


## Extra class: MLOps
| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| MLOps  | [Model Pruning](https://www.google.com/url?q=https://youtu.be/dOgaMtt_fhM&sa=D&source=editors&ust=1724832556762176&usg=AOvVaw082dQxxMvW5E1ErDrW_CVH)                   | TA Bách          | 240309-23M09-EC1   |
| MLOps  | [Mobile Deployment](https://www.google.com/url?q=https://youtu.be/z5w0806ThLU&sa=D&source=editors&ust=1724832556762460&usg=AOvVaw2ve77WcUxRREQEchr1d1zx)               | Dr. Đình Vinh    | 240316-23M09-EC1   |
| MLOps  | [Web Deployment](https://www.google.com/url?q=https://youtu.be/B55Jb7enrq8&sa=D&source=editors&ust=1724832556762742&usg=AOvVaw1aVpcvXHuHsI8toB8o4OHE)                  | Dr. Đình Vinh    | 240323-23M09-EC1   |
| MLOps  | [Deployment as a Service (API)](https://www.google.com/url?q=https://youtu.be/o0FacL81Azo&sa=D&source=editors&ust=1724832556763026&usg=AOvVaw336AdobiV4bLKxLtSA3SJq)   | TA Thắng         | 240330-23M09-EC1   |

## Seminar
| **Type**      | **Content**       | **Instructor**   | **Handout**     | **Further Reading**        |
|---------------|---------------------------------------------------|------------------|-------------------------------------------------|--------------------------------------------------|
| Seminar| [Seminar: XAI](https://www.google.com/url?q=https://youtu.be/RKcPFwzkkLs&sa=D&source=editors&ust=1724832556763354&usg=AOvVaw1KED7sW6alNyrjUl1QF8Gh)                    | Dr. Anh Nguyen   | 240405-23M09-MC    |
