---
title: Module 1 - Introduction to Python Programming
tbl-colwidths: [25,47,80,40,50,70]
css: styles.css
format:
  html:
    grid:
      body-width: 1000px
---

<div class="alert alert-dismissible alert-warning">
  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  <h4 class="alert-heading">Warning</h4>
  <p class="mb-0">This website is still under construction. Some contents and functions might temporarily not be available or not working properly</a>.</p>
</div>

# Introduction


Welcome to ***Module 1: Introduction to Python Programming*** of the AIO course. The goal of this module is to teach you basic Python programming skills, spanning from the very fundamental things like variables, functions, ... to Object-oriented Programming using Python and as well as the basic data structures. There are in total 3 assignments for the main lessons. There will also be one lecture that acts as a supplemnentary before the main lecture. 

## Projects

Regarding the projects, there are three projects where you will respectively learn how to use YOLOv8, an object detection model as well as how to use Python to manipulate and crawl data from a website. Finally, the last project is about developing simple applications using ChatGPT. In particular, the three projects are: 

- Object Detection with YOLOv8 
- Data Manipulation and Crawling 
- ChatGPT Applications 

## Competition Training

As for competition training, this module contains three lectures with the goal of teaching you the basic skills and knowledge you need before joining an AI competition, including visualizing data, knowledge about competition tasks and metrics, and design validation.

## Extra class

The central theme of the extra class for this module is about Algorithms and Complexity. In the age of AI, still, the knowledge about algorithms and their complexity including Big-O, Brute-force exhaustive, recursion, two pointer, and dynamic programming still plays an immensely important role. 


# Schedule

| Date       | Type                        | Content                                   | Instructor     | Handout                   | Further Reading                          |
|------------|-----------------------------|-------------------------------------------|----------------|---------------------------|------------------------------------------|
| 08/05/23   |          |   [Online Office Hour](https://youtu.be/UoYSU7ypz4g)                                          | Dr. Vinh       |                           |                                          |
| 28/04/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span> | [Sinh hoạt lớp](https://www.youtube.com/watch?v=95IE3oETJJ0)                             | Dr. Phúc       | [slide](https://drive.google.com/drive/folders/1Iqo7pi_szHLBKeXrhfFzw7yGqepWQyEZ)                     |                                          |
| 01/05/23   | <span class="badge rounded-pill bg-success">Assignment</span>                   | [Basic Python Exercise](https://drive.google.com/file/d/1fYfp7Audr5SJ06ys5pMy0qBcGBb7yabu/view)                      | TA Khoa        | [[solution]](https://drive.google.com/file/d/1DBsc9NKhOOaFHWNM9z4ubx-mzPqa2non/view)                |                                          |
| 03/05/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span>              | [Basic Python 1](https://www.youtube.com/watch?v=SrICKnWd4gM)                              | Dr. Vinh       | [230503 - M01ML01](https://drive.google.com/drive/folders/1TkNDyVgDn7YPv-3rN6Nn29nrKuyqgwVG) | Note    |                                          |
| 05/05/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span>              | [Basic Python 2](https://www.youtube.com/watch?v=tKws9MOQ89Y)                              | Dr. Vinh       | [230505 - M01ML02](https://drive.google.com/drive/folders/1vBQmnfQZpmHeoH452sAR4GBRQ_gCpzSj) | Note    |                                          |
| 07/05/23   | <span class="badge rounded-pill bg-info">Exercise Session</span>        | [TA-Exercise](https://www.youtube.com/watch?v=Aq48Nf6lCVY)                               | TA Khoa        | [230507 - M01ES01](https://drive.google.com/drive/folders/1uJ_vQzgES883zxJw9xE1az8lijmLrR94)          |                                          |
| 08/05/23   |<span class="badge rounded-pill bg-success">Assignment</span>                  | [Data Structure Exercise](https://drive.google.com/file/d/1eD1lWax1ObqSdo5IcSNC_-LVGeN62OWP/view)                   | Dr. Vinh       | [[solution]](https://drive.google.com/file/d/15kJD81E1R5ndm0ZJYlsFeKZVnybplRDO/viewhttps:/drive.google.com/file/d/15kJD81E1R5ndm0ZJYlsFeKZVnybplRDO/view)                |                                          |
| 10/05/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span>              | [Data Structure](https://www.youtube.com/watch?v=TK42WCKiiDw)                            | Dr. Đình Vinh  | [230510 - M01ML03](https://drive.google.com/drive/folders/1I-YUV6K7DQIWeVZr1v7icsoP-I3BuVlu)          |                                          |
| 12/05/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span>              | [Data Structure](https://www.youtube.com/watch?v=BUueswpSwVc&feature=youtu.be)                            | Dr. Đình Vinh  | [230512 - M01ML04](https://drive.google.com/drive/folders/1CYPfh30f0nQLxbHiPl-jxtNHfLkrHc5x)          |                                          |
| 14/05/23   | <span class="badge rounded-pill bg-info">Exercise Session</span>        | [TA-Exercise](https://www.youtube.com/watch?v=NsB9PjZR6G0&feature=youtu.be)                               | Dr. Vinh       | [230514 - M01ES02](https://drive.google.com/drive/folders/1-VeGlYUVMaBH3Ee98UekJHqZc3TKdLXM)          |                                          |
| 14/05/23   | <span class="badge rounded-pill bg-success">Assignment</span>                   | [Python OOP Exercise](https://drive.google.com/file/d/18UAGLZRZ1AqRDdSy_N9uXzKYRwU34Zdp/view)                       | Dr. Đình Vinh  |                           |                                          |
| 17/05/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span>              | [OOP with Python](https://www.youtube.com/watch?v=xdvi9Dzr6Qw)                           | Dr. Đình Vinh  | [230517 - M01ML05](https://drive.google.com/drive/folders/1BB5CjrmLIOcTahQg7eGO2g6UIvrigPqK)          | [Previous offering by Dr. Vinh](https://www.youtube.com/watch?si=L9C_yrUrpA1pRFH_&v=jgHnlmbr2C8&feature=youtu.be)            |
| 19/05/23   | <span class="badge rounded-pill bg-primary">Main Lesson</span>              | [OOP with Python](https://www.youtube.com/watch?v=8oDDxWeiL8A&feature=youtu.be)                           | Dr. Đình Vinh  | [230519 - M01ML06](https://drive.google.com/drive/folders/1nunyJYSXD_9k1ybzvl_fmQbxfnoRhX_K)          |                                          |
| 21/05/23   | <span class="badge rounded-pill bg-info">Exercise Session</span>        | [TA-Exercise](https://www.youtube.com/watch?v=RGPQgXzOqhg)                               | Dr. Vinh       | [230521 - M01ES03](https://drive.google.com/drive/folders/1gUZqdRAeIyqN-em8-1l0zjHKCZVIzOvT)          |                                          |
| 22/05/23   | <span class="badge rounded-pill bg-danger">Project handout</span>              | [Object Detection with YOLOv8 Project](https://drive.google.com/file/d/1bzM445pd7SMjgFgwA7hzjrjgT6Y3nmWL/view)      | TA Thắng       | [[solution]](https://drive.google.com/file/d/1bEAONvHpShFyB-LfmBSSzBsLNiWXdX-H/view)                |                                          |
| 22/05/23   | <span class="badge rounded-pill bg-danger">Project handout</span>            | [Data Manipulation and Crawling Project](https://drive.google.com/file/d/1I8WKELOqHDDFxrhSkaoAoYN1eTxlbzqn/view)    | TA Thắng       | [[solution]](https://drive.google.com/file/d/1ryoNAvV8TsZAn_PX-2PPf780zswEqGKE/view)                |                                          |
| 22/05/23   | <span class="badge rounded-pill bg-danger">Project handout</span>              | [ChatGPT Applications Project](https://drive.google.com/file/d/1h4gQH9UeItUf6UPNoRTL-nmda0fxFD3D/view)              | TA Thái        | [[solution]](https://drive.google.com/file/d/1wDuqMjj_2d3od7hkoYa2dEd9hpXc3AC2/view)                |                                          |
| 24/05/23   | <span class="badge rounded-pill bg-light">Project tutorial</span>        | [Image Project: Yolov8 for Object Detection](https://www.youtube.com/watch?v=L6Sin-ieEfM)| TA Thắng       | [230524 - M01PT01](https://drive.google.com/drive/folders/1ddidsMv8ISUrKzUViUtxnjpHwJXr6bv-)          |                                          |
| 26/05/23   | <span class="badge rounded-pill bg-light">Project tutorial</span>        | [Data Manipulation using Python Libraries](https://www.youtube.com/watch?v=LRiMeQdzDPA)  | TA Thắng       | [230526 - M01PT02](https://drive.google.com/drive/folders/11ikSSLi_Hjmt3EHlSWadFohowyxD_44U)          |                                          |
| 28/05/23   | <span class="badge rounded-pill bg-light">Project tutorial</span>        | [Text Project: ChatGPT-based Application](https://www.youtube.com/watch?v=i-fXB0CFOMY)   | TA Thái        | [230528 - M01PT03](https://drive.google.com/drive/folders/13LVFM_r7ipY-umR6b_-yAs4NiEPIWv37)          |                                          |
| 23/05/23   | <span class="badge rounded-pill bg-light">Python Support</span>         | [For, List and Dictionary](https://www.youtube.com/watch?v=_WkMMGINOVA)                  | TA Tiềm        | [230523 - M02CR01](https://drive.google.com/drive/folders/1mEwkeD_DAaDMoBVY44zjhl4B15snHTcd)          |                                          |
| 11/05/23   | <span class="badge rounded-pill bg-warning">Competition</span>                  | [Data Visualization](https://www.youtube.com/watch?v=BtAIW83TCvc)                        | TA Hùng        | [230511 - M01AC01](https://drive.google.com/drive/folders/1p1s-HXHjuwZyRDyWhZqkDiIkeAa93Rlq)          |                                          |
| 18/05/23   |<span class="badge rounded-pill bg-warning">Competition</span> | [Competition tasks and metrics](https://www.youtube.com/watch?v=98JL_UFpxlQ)                                          |       TA Hùng          | [230518 - M01AC02](https://drive.google.com/drive/folders/1TZvYRpntsLQdYhKieewtItkAo3YhfBbp)          |         |
| 25/05/23   | <span class="badge rounded-pill bg-warning">Competition</span>                  | [Design Validation](https://www.youtube.com/watch?v=TyVCXo45c1Y)                         |      TA Hùng           | [230525 - M01AC03](https://drive.google.com/drive/folders/1WnLoiazazGWNxKtmt9IjH0ppAikqtLpk)          |                                          |
| 06/05/23   | <span class="badge rounded-pill bg-dark">Algorithms & Complexity</span> | [Big-O (Time analysis)](https://www.youtube.com/watch?v=i97kAPZtq4A)                     | TA Thái        | [230506 - M01EC01](https://drive.google.com/drive/folders/1yof63zCXcoyIIZWvU2CQ4cYWOPIGeT-H)          |                                        |
| 13/05/23   | <span class="badge rounded-pill bg-dark">Algorithms & Complexity</span>    | [Brute-force Exhaustive](https://www.youtube.com/watch?v=4J3D5it9ugA)                    |  TA Thái              | [230513 - M01EC02](https://drive.google.com/drive/folders/1deNcaXHYAbE5A3cgKKv1z7wUAdLmfcC6)          |                                          |
| 20/05/23   | <span class="badge rounded-pill bg-dark">Algorithms & Complexity</span>    | [Recursion and Two Pointer](https://www.youtube.com/watch?v=dOrQveeQz90)                 |  TA Thái        | [230520 - M01EC03](https://drive.google.com/drive/folders/1EmyHR-SB0L1Lw5OYUQw770iLfuKB1JxZ)          |                                          |
| 27/05/23   | <span class="badge rounded-pill bg-dark">Algorithms & Complexity</span>    | [Dynamic Programming](https://www.youtube.com/watch?v=38gV3ggD0Pg)                       |    TA Thái              | [230527 - M01EC04](https://drive.google.com/drive/folders/1aEtoJ-i6WbrmA7_-xDXIIhcpjMBzvFch)          |                                       |
:   {.striped .hover}

# Further Resources

- Sweigart, Al. *Beyond the basic stuff with python: Best practices for writing clean code*. No Starch Press, 2020.
- [Object-Oriented Programming (OOP) in Python 3](https://realpython.com/python3-object-oriented-programming/)

- [Huyen Chip's GitHub repository](https://github.com/chiphuyen/python-is-cool)
 
- [Stanford's CS161 Design and Analysis of Algorithms course](https://web.stanford.edu/class/archive/cs/cs161/cs161.1138/)
