---
title: Module 5 - Deep Learning Prerequisites
tbl-colwidths: [25,35,105,40,40,70]
css: styles.css
format:
  html:
    grid:
      body-width: 1000px
    smooth-scroll: true
    fontsize: 0.85em
title-block-banner: true
---

# Introduction

# Course Schedule and Material

## Main lessons

| Date| Type  | Content| Instructor   | Handout | Further Reading|
|------------|-----------------------------|--------------------------------------------------------------|--------------|---------|-----------------------------------| 
| 02/10/23| <span class="badge rounded-pill bg-success">Assignment</span>| Logistic Regression Exercise | TA Thắng| [solution] |  |
| 04/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [From Linear Regression to Logistic Regression](https://www.youtube.com/watch?v=77Jo-MGfCpQ) | Dr. Vinh| 231004  |  |
| 06/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Logistic Regression - Vectorization and Applications](https://www.youtube.com/watch?v=DuCyzgXdsGg)| Dr. Vinh| 231006  | [Jurafsky et al., C5, 2023]|
| 08/10/23| <span class="badge rounded-pill bg-info">Exercise Session</span></span>| [TA Exercise](https://www.youtube.com/watch?v=ngK3XWEsihY)| TA Thắng| 231008  |  |
| 09/10/23| <span class="badge rounded-pill bg-success">Assignment</span>| Softmax Regression Exercise  | TA Thắng| [solution] |  |
| 11/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| S[oftmax Regression (Multiclass Classification)](https://www.youtube.com/watch?v=h1k_WvkSOAk)| Dr. Vinh| 231011  |  |
| 13/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>|[ Pytorch Framework (Implementation for regression)](https://www.youtube.com/watch?v=SmN9nNY_EdU)  | Dr. Vinh| 231013  |  |
| 15/10/23| <span class="badge rounded-pill bg-info">Exercise Session<span> | [TA Exercise](https://www.youtube.com/watch?v=CogEVblthW4)| TA Khoa | 231015  |  |
| 16/10/23| <span class="badge rounded-pill bg-success">Assignment</span>| MLP Exercise | TA Thắng| [Exercise] |  |
| 18/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Multilayer Perceptron](https://www.youtube.com/watch?v=oHI-wneEUCM) | Dr. Vinh| 231018  |  |
| 20/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Activations and Initializers](https://www.youtube.com/watch?v=x0EeokfjStg) | Dr. Vinh| 231020  |  |
| 22/10/23| <span class="badge rounded-pill bg-info">Exercise Session<span>| [TA Exercise](https://www.youtube.com/watch?v=YsQwmjb0x-Y)| TA Khoa | 231022  |  |
| 25/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Optimizers for Neural Network (1)](https://www.youtube.com/watch?v=pyA-wXMYzKQ)| Dr. Vinh| 231025  |  |
| 27/10/23| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Optimizers for Neural Networks (2)](https://www.youtube.com/watch?v=VinG-BqGlu4) | Dr. Vinh| 231027  |  |
| 29/10/23| <span class="badge rounded-pill bg-info">Exercise Session</span>    | [TA-Exercise (Optimization methods)](https://www.youtube.com/watch?v=sdHnsRY4YKs)| TA Khoa | 231029  |  |
| 01/11/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Text data: Sentiment Analysis](https://www.youtube.com/watch?v=2twDuxyITrk)| TA Thái | 231101  |  |
| 03/11/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Time-series Data Project: Music Genre Classification](https://www.youtube.com/watch?v=Ud9BKnL3PpE)| TA Bảo| 231103  |  |
| 05/11/23| <span class="badge rounded-pill bg-success">Project Tutorial</span> | [Image Data Project: Gradient Vanishing in MLP](https://www.youtube.com/watch?v=ii7dSVQcBHI) | TA Khoa | 231105  |  |

## Python Tutorial Session 

| Date| Type  | Content| Instructor   | Handout | Further Reading|
|------------|-----------------------------|--------------------------------------------------------------|--------------|---------|-----------------------------------|   
| 03/10/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Logistic Regression](https://www.youtube.com/watch?v=aRde10ggswo)| TA Thái | 231003  |  |
| 10/10/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Softmax Regression](https://www.youtube.com/watch?v=79rw9-xp23M)|   | 231010  |  |
| 17/10/23| <span class="badge rounded-pill bg-primary">Preview</span>| [Multilayer Perceptron](https://www.youtube.com/watch?v=-rPw8CrHlpM) |   | 231017  |  |
| 24/10/23| <span class="badge rounded-pill bg-primary">Preview</span>| [SGD+Momentum](https://www.youtube.com/watch?v=_ST8NTvuCZw) |   | 231024  |  |

## Extra class: Introduction to Computer Vision 
      
| Date| Type  | Content| Instructor   | Handout | Further Reading|
|------------|-----------------------------|--------------------------------------------------------------|--------------|---------|-----------------------------------|   
| 07/10/23|  <span class="badge rounded-pill bg-info">Computer Vision</span>| [Introduction to CV and Background subtraction](https://www.youtube.com/watch?v=PNb4b4UalzM) | Dr. Đình Vinh| 231007  |  |
| 14/10/23|  <span class="badge rounded-pill bg-info">Computer Vision</span>| [Lane Detection](https://www.youtube.com/watch?v=1s4zpNKhc0M)    |Dr. Đình Vinh   | 231014  |  |
| 21/10/23|  <span class="badge rounded-pill bg-info">Computer Vision</span>| [Image Stitching (panorama)](https://www.youtube.com/watch?v=W0w_9X51MGs)   |Dr. Đình Vinh   | 231021  |  |
| 28/10/23|  <span class="badge rounded-pill bg-info">Computer Vision</span>| [Face Detection](https://www.youtube.com/watch?v=yVIF_5JC1RA)    | Dr. Đình Vinh  | 231028  |  |
| 04/11/23|  <span class="badge rounded-pill bg-info">Computer Vision</span>| [Object Tracking using Mean Shift/Cam Shift](https://www.youtube.com/watch?v=o_RLl9rV320)  | Dr. Đình Vinh  | 231104  |  |

## Competition Training

| Date| Type  | Content| Instructor   | Handout | Further Reading|
|------------|-----------------------------|--------------------------------------------------------------|--------------|---------|-----------------------------------| 
| 05/10/23| <span class="badge rounded-pill bg-warning">Competition</span>    | [Introduction to Imbalance Data](https://www.youtube.com/watch?v=u8iO6_gRq24)| TA Hùng | 231005  |  |
| 12/10/23| <span class="badge rounded-pill bg-warning">Competition</span>    | [Model Evaluation](https://www.youtube.com/watch?v=1E-qylhIoWg)  |TA Hùng   | 231012  |  |
| 19/10/23| <span class="badge rounded-pill bg-warning">Competition</span>    | [Kalapa Challenge](https://www.youtube.com/watch?v=DlPeejlTRQo)  | TA Hùng  | 231019  |  |
| 02/11/23| <span class="badge rounded-pill bg-warning">Competition</span>    | [Data Sampling](https://www.youtube.com/watch?v=E8y6uNJBUa8)| TA Hùng  | 231102  |  |

# Further Resources