---
title: Module 7 - Advanced Model Architectures for Computer Vision
tbl-colwidths: [35,120,30,50,70]
css: styles.css
format:
  html:
    grid:
      body-width: 1000px
    smooth-scroll: true
    fontsize: 0.85em
title-block-banner: true
---

# Course Schedule and Material

## Main lessons
| Type  | Content     | Instructor   | Handout| Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-success">Assignment</span>| Domain Conversion Exercise       | TA Khoa      |        |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Domain Conversion - Denoising and Segmentation](https://www.google.com/url?q=https://youtu.be/lMs32sF7Ayo&sa=D&source=editors&ust=1724832556752327&usg=AOvVaw2nPS3yrULkk3EoPzpkn_9D)         | Dr. Vinh     | 231220-23M07MC    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Domain Conversion - Colorization and Super Resolution](https://www.google.com/url?q=https://youtu.be/HqrKcKr7BO0&sa=D&source=editors&ust=1724832556752684&usg=AOvVaw25WYU9ymXVUyjBW4HTr5__)  | Dr. Vinh     | 231222-23M07MC    |      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA Exercise](https://www.google.com/url?q=https://youtu.be/SdLFbq0lYwc&sa=D&source=editors&ust=1724832556753025&usg=AOvVaw0L-_lVsg99GtcsY1NvfzGm)| TA Khoa      | 231224-23M07MC    |      |
| <span class="badge rounded-pill bg-success">Assignment</span>| Object Detection Project         | TA Hùng      |        |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection (1)](https://www.google.com/url?q=https://youtu.be/1lCS9lpqcwo&sa=D&source=editors&ust=1724832556753477&usg=AOvVaw05TT_aybHs4-mc0gXGpGcD)  | Dr. Đình Vinh| 231227-23M07MC    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection (2)](https://www.google.com/url?q=https://youtu.be/0S3NRo118pA&sa=D&source=editors&ust=1724832556753747&usg=AOvVaw1dFqs2hpS84f_q-CkDq4Lr)  | Dr. Đình Vinh| 231229-23M07MC    |      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA Exercise](https://www.google.com/url?q=https://youtu.be/MC0g875zbZU&sa=D&source=editors&ust=1724832556754002&usg=AOvVaw2wPVT9yvyzpWcCz56yVGli)| TA Hùng      | 231231-23M07MC    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection](https://www.google.com/url?q=https://youtu.be/BoXXy_24Lc4&sa=D&source=editors&ust=1724832556754261&usg=AOvVaw3YcTNTXecEgD89iyJ9pNlu)      | Dr. Đình Vinh| 240103-23M07MC    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Object Detection](https://www.google.com/url?q=https://youtu.be/vqhLNzVFPN4&sa=D&source=editors&ust=1724832556754478&usg=AOvVaw3_dqLha10ZCEje5MkjVXWk)      | Dr. Đình Vinh| 240105-23M07MC    |      |
| <span class="badge rounded-pill bg-info">Exercise Session</span>| [TA-Exercise](https://www.google.com/url?q=https://youtu.be/I_4SNAs2l0w&sa=D&source=editors&ust=1724832556754724&usg=AOvVaw1CGcyQHJDsv8SJIlmX2RUS)| TA Hùng      | 240107-23M07MC    |      |
| <span class="badge rounded-pill bg-success">Assignment</span>| Imbalanced Data Exercise         |   |        |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Advanced Topic: Imbalanced Data](https://www.google.com/url?q=https://youtu.be/TXl74SdQys0&sa=D&source=editors&ust=1724832556755242&usg=AOvVaw3voqJI8kulgr0fty9gvCtr)  | Dr. Vinh     | 240110-23M07MC    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Advanced Topic: Self/semi-supervised Learning](https://www.google.com/url?q=https://youtu.be/VYcjApR35lo&sa=D&source=editors&ust=1724832556755674&usg=AOvVaw1rbuCRijlOhp3NVL5Se5du)          | Dr. Hưng     | 240112-23M07MC    |      |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>| [Advanced Topic: Knowledge Distillation](https://www.google.com/url?q=https://youtu.be/nZIo5YtcwU4&sa=D&source=editors&ust=1724832556755972&usg=AOvVaw3Ahk7_yQcB548Y598ys27_)      | Dr. Hưng     | 240114-23M07MC    |      |
|  <span class="badge rounded-pill bg-success">Project tutorial</span>| [Image Project: Tracking by Detection](https://www.google.com/url?q=https://youtu.be/TIZ5VBodinM&sa=D&source=editors&ust=1724832556756257&usg=AOvVaw1SQxTyBhFLR5zAoY8O0qe3)        | TA Thắng     | 240117-23M07MC    |      |
|  <span class="badge rounded-pill bg-success">Project tutorial</span>| [Image Project: Medical Image Analysis (1)](https://www.google.com/url?q=https://youtu.be/bHqXK3_0aBY&sa=D&source=editors&ust=1724832556756644&usg=AOvVaw2M5s_PG76UDtpUI9GxBi8b)   | TA Huy       | 240119-23M07MC    |      |
|  <span class="badge rounded-pill bg-success">Project tutorial</span>| [Image Project: Medical Image Analysis (2)](https://www.google.com/url?q=https://youtu.be/EMbMuSw8-EU&sa=D&source=editors&ust=1724832556756906&usg=AOvVaw2ziZisD133bi-pBZDvg7bd)   | TA Huy       | 240121-23M07MC    |      |


## Lesson preview
| Type  | Content     | Instructor   | Handout| Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| <span class="badge rounded-pill bg-primary">Preview</span>          | [UNet](https://www.google.com/url?q=https://youtu.be/q3HfysdFV-U&sa=D&source=editors&ust=1724832556757226&usg=AOvVaw2p0S1NWf1AoUVsA6HnxZjs)       | TA Thái      | 231219-23M07-EC2  |      |
| <span class="badge rounded-pill bg-primary">Preview</span>      | [Object Detection using Pretrained Models](https://www.google.com/url?q=https://youtu.be/2hf3t_cRc7A&sa=D&source=editors&ust=1724832556757522&usg=AOvVaw1Z0GzfqQJKdpZETBEezCx4)    | TA Thái  | 231226-23M07-EC2  |      |
| <span class="badge rounded-pill bg-primary">Preview</span>      | [Yolov1](https://www.google.com/url?q=https://youtu.be/3ABkT9mFPZU&sa=D&source=editors&ust=1724832556757744&usg=AOvVaw0M2qRU_8IWSc3hAF679kIf)     |TA Thái   | 240102-23M07-EC2  |      |
| <span class="badge rounded-pill bg-primary">Preview</span>      | [Introduction to Imbalanced Data](https://www.google.com/url?q=https://youtu.be/nQMrb7ySnIk&sa=D&source=editors&ust=1724832556757910&usg=AOvVaw3h4TXjckQU2nTSbF8w8oBz)  |TA Thái   | 240109-23M07-EC2  |      |
||          

## Extra Class: Research and Paper Writing

| Type  | Content     | Instructor   | Handout| Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| Research & Paper| [Group Report (1)](https://www.google.com/url?q=https://youtu.be/G48uhvxE4hY&sa=D&source=editors&ust=1724832556758243&usg=AOvVaw00rTYaaJOQsx8idQATEg7K)      | Dr. Đình Vinh| N/A    |      |
| Research & Paper| [Group Report (2)](https://www.google.com/url?q=https://youtu.be/BoGSS29KXuU&sa=D&source=editors&ust=1724832556758437&usg=AOvVaw3gXuUW36v4aD0tTeEVXg-P)      | Dr. Đình Vinh  | N/A    |      |
| Research & Paper| [How to Write a Paper (1)](https://www.google.com/url?q=https://youtu.be/Ptmf7UQMsuU&sa=D&source=editors&ust=1724832556758642&usg=AOvVaw2eSi_ZC9gBovPvKbLxVRur)         |Dr. Đình Vinh   | 240106-23M07-EC1  |      |
| Research & Paper| [How to Write a Paper (2)](https://www.google.com/url?q=https://youtu.be/gjjX-6QoGvo&sa=D&source=editors&ust=1724832556758904&usg=AOvVaw0AosTO3gzffzTe1LahpVyi)         | Dr. Đình Vinh  | 240113-23M07-EC1  |      |

## Seminars

| Type  | Content     | Instructor   | Handout| Further Reading |
|-----------------------------|-------------------------------------------------------------------|--------------|-------------------|-----------------|
| Seminar          | [Advanced UNet and LLMs Introduction](https://www.google.com/url?q=https://youtu.be/bip6qL9jsZM&sa=D&source=editors&ust=1724832556759145&usg=AOvVaw3mDXVXsQzjovpxqMZPLCnP)         | Dr. Vinh     | 231224-23M07-EC3  |      |
| Seminar          | [Seminar: Multimodal Language Models](https://www.google.com/url?q=https://youtu.be/rFFXkGvzaVw&sa=D&source=editors&ust=1724832556759442&usg=AOvVaw34zm135l8ihXRwj8ooQnE1)         |   | 231231-23M07-EC3  |      |
| Seminar          | [Seminar: Visual Instruction Tuning (LlaVa) and QLoRA](https://www.google.com/url?q=https://youtu.be/_Gfk1EFlOIo&sa=D&source=editors&ust=1724832556759755&usg=AOvVaw2K0iG5QBFhF3mKLii7c-SS)   |   | 240107-23M07-EC3  |      |
| Seminar          | [Data Augmentation and Imbalanced Data](https://www.google.com/url?q=https://youtu.be/7PikDIQWB6c&sa=D&source=editors&ust=1724832556760026&usg=AOvVaw1CCsVBU9JbEoZ5wsPIpqUy)       |   | 240114-23M07-EC3  |      |
| Seminar          | [RNN-based Forecasting and Toolformer](https://www.google.com/url?q=https://youtu.be/NkFczM4yz-A&sa=D&source=editors&ust=1724832556760277&usg=AOvVaw2blH_AYhhpf3hcg_jL-lCJ)        |   | 240121-23M07-EC3  |      |
