---
title: Module 10 - Reinforcement Learning, GNN, and LLMs
tbl-colwidths: [35,120,30,50,70]
css: styles.css
format:
  html:
    grid:
      body-width: 1000px
    smooth-scroll: true
    fontsize: 0.85em
title-block-banner: true
---

# Course Schedule and Resources

## Main lessons

| Type| Content   | Instructor     | Handout      | Further Reading   |
|-------------|------------------------------------------------------------------|----------------|--------------|--------------------------------------------|
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | <span class="badge rounded-pill bg-success">Assignment</span>: Reinforcement Learning Exercise     | TA Thắng|      |   |
| Preview     | [Introduction to Reinforcement Learning](https://www.google.com/url?q=https://youtu.be/67cUGpOdwjI&sa=D&source=editors&ust=1724832556757768&usg=AOvVaw1ZKGSFwGyq_pYtQjufI0k8)  | TA Thuận| 240416-23M10-EC2 |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Reinforcement Learning (CartPole)](https://www.google.com/url?q=https://youtu.be/OgYC_dXWyc8&sa=D&source=editors&ust=1724832556758230&usg=AOvVaw26cP3G_j_j-AYw3tSn6veP)| Dr. Hoàng      | 240417-23M10-MC |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Reinforcement Learning (Deep Deterministic Policy Gradient)](https://www.google.com/url?q=https://youtu.be/0KOuk0VVxYo&sa=D&source=editors&ust=1724832556758621&usg=AOvVaw2C_t_jlZJEwuo0WyPqnvHs)      | Dr. Hoàng      | 240419-23M10-MC |   |
| Exercise    | [TA Exercise](https://www.google.com/url?q=https://youtu.be/LWBdqHG1Hw0&sa=D&source=editors&ust=1724832556758947&usg=AOvVaw3jUsTGp48gtfP6kL6rny2T)    | TA Thắng| 240421-23M10-MC |   |
| <span class="badge rounded-pill bg-success">Assignment</span>  | [Point Cloud Techniques and Applications Project](https://www.google.com/url?q=https://drive.google.com/file/d/1lFg_T25zN6mFtfVip9ZgzpQCQ_zs3Kml/view&sa=D&source=editors&ust=1724832556759379&usg=AOvVaw2nitD77Jb_ojpjlJ_15ob1) | Dr. Tuấn|      |   |
| <span class="badge rounded-pill bg-success">Assignment</span>  | [Multimodal Large Language Models Exercise](https://www.google.com/url?q=https://drive.google.com/file/d/18TSBb1upiJkj3H8CxXD8MYV10LK7M1cj/view&sa=D&source=editors&ust=1724832556759677&usg=AOvVaw0EAXIP7rj04ZoIlsdXGY10)| TA Thái|      |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Classification for 3D Point Cloud Data](https://www.google.com/url?q=https://youtu.be/ebQ3e8pGSSE&sa=D&source=editors&ust=1724832556760032&usg=AOvVaw3xftg57Gb9hORBWYqSfUcI)  | Dr. Tuấn| 240424-23M10-MC |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [Advances in 3D Point Cloud Data](https://www.google.com/url?q=https://youtu.be/US2o866dCh8&sa=D&source=editors&ust=1724832556760424&usg=AOvVaw1wHJ2Jk2LwHAEECszJiJwu) | Dr. Tuấn| 240426-23M10-MC |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [GNN Node Classification](https://www.google.com/url?q=https://youtu.be/f1YQCJ9OfgI&sa=D&source=editors&ust=1724832556760734&usg=AOvVaw0t7NuHJBqThc1VIUxnkjKC) | Dr. Đình Vinh  | 240428-23M10-MC |   |
| <span class="badge rounded-pill bg-primary">Main Lesson</span>  | [GNN (Molecular Property Prediction)](https://www.google.com/url?q=https://youtu.be/OXxorkP-GKg&sa=D&source=editors&ust=1724832556761121&usg=AOvVaw0_05w28OfjzjKRMll9Ev5k)     | Dr. Đình Vinh  | 240501-23M10-MC |   |
| Exercise    | [TA Exercise](https://www.google.com/url?q=https://youtu.be/wlwqCc3kgUY&sa=D&source=editors&ust=1724832556761471&usg=AOvVaw3LCvMLSrE6z6Dy9O4GjQPv)    | TA Đức | 240503-23M10-MC |   |
| Project PT  | [Multitasking networks for Vision](https://www.google.com/url?q=https://youtu.be/zEEeuu6cA80&sa=D&source=editors&ust=1724832556761794&usg=AOvVaw2GHRbS3SlwvMrD4cbw4c6j)| TA Thái| 240505-23M10-MC | [Exercise]|
| Project PT  | [VideoCLIP for Video Classification](https://www.google.com/url?q=https://youtu.be/mB0nSmeDWLs&sa=D&source=editors&ust=1724832556762206&usg=AOvVaw3eA3yVr2aqPIpRpGx8YXuQ)      | TA Đức | 240508-23M10-MC |   |
| Project PT  | [Multi-agent LLM](https://www.google.com/url?q=https://youtu.be/TPc3ZGj4vZs&sa=D&source=editors&ust=1724832556762512&usg=AOvVaw3-dK_8oIDqDk98DTijAuZW)| TA Thắng| 240510-23M10-MC |   |

##  Extra class: Introduction to Large Language Models (LLMs)

| Type| Content   | Instructor     | Handout      | Further Reading   |
|-------------|------------------------------------------------------------------|----------------|--------------|--------------------------------------------|
| Extra class | [LLM RAG for Applications](https://www.google.com/url?q=https://youtu.be/QM7_Xq6SzdE&sa=D&source=editors&ust=1724832556762972&usg=AOvVaw1l34gxUvn2cWrQhVIvNu2r)| TA Bách| 240421-23M10-MC |   |
| Extra class | [LLMs for Multimodal Data](https://www.google.com/url?q=https://youtu.be/14NHUCkTntk&sa=D&source=editors&ust=1724832556763321&usg=AOvVaw2ZozFP7k1w1U8e3tPMOQA7)| TA Thái| 240427-23M10-EC1 | [Modaverse] [BLIP-2] [NExT-GPT]    |
| Extra class | [LLM Deployment with LangChain](https://www.google.com/url?q=https://youtu.be/ndwR4byDvbQ&sa=D&source=editors&ust=1724832556763803&usg=AOvVaw06ILRVWpJDXkgCGFCXRa8k)   | TA Thắng| 240504-23M10-EC1 |   |
