---
title: Courses
title-block-banner: true
description: A compilation of freely available AI courses on the Internet.
tbl-colwidths: [20,70,35,30,30]
---

## Probability and Statistics
| Difficulty  | Course                                                   | University         | Additional Resources          | Lecture            |  
|-------------|-----------------------------------------------------------|--------------------|--------------------|--------------------|
| Medium      | Stat110: Probability                                      | Harvard University | Joe Blitzstein     | Youtube Playlist   |
| Easy        | CS109: Probability for Computer Scientists                | Stanford University| [PDF Note](https://web.stanford.edu/~mossr/pdf/p4cs.pdf)       | Youtube Playlist   | 
| Medium      | Stats 116: Introduction to Probability                    | Stanford University|                    | [ ]                |
| Medium      | Math 131B: Introduction to Probability and Statistics     | UC Irvine          | Lectures           | [x]                |
| Difficult   | Stats 300B: Theory of Statistics II                       | Stanford University|                    | [ ]                |
| Difficult   | Statistics 305a: Applied Statistics (Linear Models and More)| Stanford University|                    | [ ]                |

## Optimization
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Extreme     | EE364A: Convex Optimization I                             | Stanford University|                      | Lecture            |
| Difficult   | EE364m: The Mathematics of Convexity                      | Stanford University|                      | [ ]                |

## Machine Learning
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Medium      | CS189/289A Introduction to Machine Learning               | UC Berkeley        |                      | [ ]                |
| Medium      | CS 4/5780: Intro to Machine Learning                      | Cornell University |                      | [ ]                |
| Medium      | 10-301 Introduction to Machine Learning                   | Carnegie Mellon University |                | [ ]                |

## Deep Learning
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Medium      |CS W182/282A Designing, Visualizing and Understanding Deep Neural Networks  | UC Berkeley        |                      | [ ]                |
| Difficult   |CS294-158 Deep Unsupervised Learning  | UC Berkeley        |                      | [Youtube PLaylist](https://www.youtube.com/playlist?list=PLwRJQ4m4UJjPIvv4kgBkvu_uygrV3ut_U)                |


## NLP
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Medium      | CS224N: Natural Language Processing with Deep Learning    | Stanford University|                      | [ ]                |
| Medium      | CS224U: Natural Language Understanding                    | Stanford University|                      | [ ]                |
| Medium      | [CS288: Natural Language Processing](https://cal-cs288.github.io/sp22/)                    | Caltech|                      | [ ]                |
| Difficult   | 11-711 Advanced Natural Language Processing               | Carnegie Mellon University |                | [ ]                |

## LLMs
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Medium      | COS 597G: Understanding Large Language Models             | Princeton University| (No lecture video)   | [ ]                |
| Medium      | COS584: Advanced Natural Language Processing              | Princeton University| (No lecture video)   | [ ]                |
| Medium      | CS324: Large Language Models                              | Stanford University|                      | [ ]                |
| Medium      | CS 329X: Human-Centered NLP                               | Stanford University|                      |                    |

## Computer Vision
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Medium      | CS231N: Deep Learning for Computer Vision                 | Stanford University|                      | [ ]                |
| Medium      | [CS280: Graduate Computer Vision](https://cs280-berkeley.github.io/)                 | UC Berkeley |                      | [ ]                |

## Multimodal / Others
| Difficulty  | Course                                                   | University         | Additional Resources | Lecture            |
|-------------|-----------------------------------------------------------|--------------------|----------------------|--------------------|
| Medium      | CS236: Generative Models                                  | Stanford University|                      | [ ]                |
| Difficult   | Stat 241B / CS 281B: Advanced Topics in Statistical Learning | UC Berkeley      |                      | [ ]                |
